Document: quantlibswig
Title: Debian quantlibswig Manual
Author: <insert document author here>
Abstract: This manual describes what quantlibswig is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/quantlibswig/quantlibswig.sgml.gz

Format: postscript
Files: /usr/share/doc/quantlibswig/quantlibswig.ps.gz

Format: text
Files: /usr/share/doc/quantlibswig/quantlibswig.text.gz

Format: HTML
Index: /usr/share/doc/quantlibswig/html/index.html
Files: /usr/share/doc/quantlibswig/html/*.html
