all:
	cd ObjectHandler && $(MAKE)
	cd ObjectClassLibrary && $(MAKE)
	cd Addins/C++ && $(MAKE)
	cd Clients/C++ && $(MAKE)

clean:
	cd ObjectHandler && $(MAKE) clean
	cd ObjectClassLibrary && $(MAKE) clean
	cd Addins/C++ && $(MAKE) clean
	cd Clients/C++ && $(MAKE) clean
