/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <ql/experimental/xva/gaussian1dscenariogenerator.hpp>
#include <ql/experimental/xva/scenariogenerator.hpp>

