/* qla/config.hpp.  Generated by configure.  */
/* qla/config.hpp.in.  Generated from configure.ac by autoheader.  */

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Name of package */
#define PACKAGE "QuantLibAddin"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "quantlib-dev@lists.sourceforge.net"

/* Define to the full name of this package. */
#define PACKAGE_NAME "QuantLibAddin"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "QuantLibAddin 0.3.13"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "QuantLibAddin"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.3.13"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "0.3.13"
