/*
 Copyright (C) 2006 Ferdinando Ametrano

 This file is part of QuantLib, a free-software/open-source library
 for financial quantitative analysts and developers - http://quantlib.org/

 QuantLib is free software: you can redistribute it and/or modify it under the
 terms of the QuantLib license.  You should have received a copy of the
 license along with this program; if not, please email quantlib-dev@lists.sf.net
 The license is also available online at http://quantlib.org/html/license.html

 This program is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE.  See the license for more details.
*/

/*! \file
    \brief math utility functions defined in math.xml

    The functions implemented in this file are invoked in the Addins from code
    autogenerated by srcgen.py.
*/

#ifndef qla_math_hpp
#define qla_math_hpp

#include <oh/objhandler.hpp>
#include <ql/Functions/mathf.hpp>

namespace QuantLibAddin {

/*! \group math
    math utility functions for QuantLibAddin
*/

    /*! return the N-th prime number
    */
    inline long qlPrimeNumber(const QuantLib::Size index) {
        return QuantLib::primeNumbers(index);
    }    



}

#endif

