QT     -= core gui
TEMPLATE = lib
CONFIG += static
CONFIG -= debug_and_release
CONFIG += create_prl
CONFIG -= app_bundle
CONFIG(debug, debug|release) {
    CONFIG -= release
    CONFIG += debug
    TARGET = quantlibd
    OBJECTS_DIR = ../quantlib-build/debug
} else {
    CONFIG -= debug
    CONFIG += release
    TARGET = quantlib
    OBJECTS_DIR = ../quantlib-build/release
}
DESTDIR = lib
VERSION = 1.3

gcc {
    message(gcc)
    QMAKE_CXXFLAGS += -std=c++11
    #QMAKE_CXXFLAGS += -lstdc++
    #QMAKE_CXXFLAGS += -pthread
    #LIBS += -pthread
}
macx-g++ {
    message(macx-g++)
}
macx-clang {
    message(macx-clang)
}



# Boost Library
#g++ -I/opt/local/include/ -I/opt/local/include/boost BermudanSwaption.cpp \
#    -o bermudanswaption -L/opt/local/lib/ -lQuantLib
macx {
    INCLUDEPATH += /opt/local/include /opt/local/include/boost
    LIBS += -L/opt/local/lib -lboost_timer-mt -lboost_thread-mt
}
win32-msvc* {
    INCLUDEPATH += C:/boost/boost_1_53_0
    CONFIG(debug, debug|release) {
        LIBS += C:/boost/boost_1_53_0/lib/libboost_timer-vc100-mt-gd-1_53.lib
    } else {
        LIBS += C:/boost/boost_1_53_0/lib/libboost_timer-vc100-mt-1_53.lib
    }
}
win32-g++ {
    INCLUDEPATH += C:/boost/boost_1_53_0
    CONFIG(debug, debug|release) {
        LIBS += C:/boost/boost_1_53_0/lib/libboost_timer-mgw47-mt-d-1_53.a
    } else {
        LIBS += C:/boost/boost_1_53_0/lib/libboost_timer-mgw47-mt-1_53.a
    }
}
#unix {
#    INCLUDEPATH += /home/deriversatile/boost/boost_1_53_0
#    CONFIG(debug, debug|release) {
#        #LIBS += -L/home/algefrontal/boost/boost_1_50_0/libd -lboost_timer-mt-d
#        LIBS += -L/home/deriversatile/boost/boost_1_53_0/lib -lboost_timer-mt-d
#    } else {
#        #LIBS += -L/home/algefrontal/boost/boost_1_50_0/lib -lboost_timer-mt
#        LIBS += -L/home/deriversatile/boost/boost_1_53_0/lib -lboost_timer-mt
#    }
#}


# QuantLib
macx {
    INCLUDEPATH += ~/Documents/QuantLib/quantlib/QuantLib/
#    CONFIG(debug, debug|release) {
#        #LIBS += -L/opt/local/lib/ -lQuantLib
#        LIBS += -L/Users/osx/Documents/QuantLib/quantlib/build-QuantLib-Desktop_Qt_5_0_2_clang_64bit-Debug/lib -lquantlibd
#    } else {
#        #LIBS += -L/opt/local/lib/ -lQuantLib
#        LIBS += -L/Users/osx/Documents/QuantLib/quantlib/build-QuantLib-Desktop_Qt_5_0_2_clang_64bit-Release/lib -lquantlib
#    }
}
win32-msvc* {
    INCLUDEPATH += C:/QuantLib/QuantLibQt
#    CONFIG(debug, debug|release) {
#        LIBS += C:/QuantLib/QuantLibQt/lib/QuantLib-vc100-mt-gd.lib
#    } else {
#        LIBS += C:/QuantLib/QuantLibQt/lib/QuantLib-vc100-mt.lib
#    }
}
win32-g++ {
    INCLUDEPATH += C:/QuantLib/QuantLibQt
#    CONFIG(debug, debug|release) {
#        LIBS += C:/QuantLib/QuantLibQt/lib/libQuantLibQtd.a
#    } else {
#        LIBS += C:/QuantLib/QuantLibQt/lib/libQuantLibQt.a
#    }
}

#unix {
#    #INCLUDEPATH += /home/algefrontal/QuantLib/QuantLibQt
#    #INCLUDEPATH += ../QuantLibQt
#    #INCLUDEPATH += /home/deriversatile/QuantLibXPS14ub/QuantLibQt
#    INCLUDEPATH += /home/deriversatile/QuantLib/quantlib
##    CONFIG(debug, debug|release) {
##        LIBS += -L/home/deriversatile/QuantLib/QuantLibQt/lib -lQuantLibQtd
##    } else {
##        LIBS += -L/home/deriversatile/QuantLib/QuantLibQt/lib -lQuantLibQt
##    }
#}

#win32:QMAKE_CXXFLAGS_DEBUG += /Warning:disable(4819)
win32-msvc* {
    #QMAKE_CXXFLAGS += /wd4819 /wd4101 /wd4102 /wd4189 /wd4996
    QMAKE_CXXFLAGS += /wd4819
}



SOURCES += \
ql/math/randomnumbers/primitivepolynomials.c \
ql/cashflow.cpp \
ql/cashflows/averagebmacoupon.cpp \
ql/cashflows/capflooredcoupon.cpp \
ql/cashflows/capflooredinflationcoupon.cpp \
ql/cashflows/cashflows.cpp \
ql/cashflows/cashflowvectors.cpp \
ql/cashflows/cmscoupon.cpp \
ql/cashflows/conundrumpricer.cpp \
ql/cashflows/coupon.cpp \
ql/cashflows/couponpricer.cpp \
ql/cashflows/cpicoupon.cpp \
ql/cashflows/cpicouponpricer.cpp \
ql/cashflows/digitalcmscoupon.cpp \
ql/cashflows/digitalcoupon.cpp \
ql/cashflows/digitaliborcoupon.cpp \
ql/cashflows/dividend.cpp \
ql/cashflows/duration.cpp \
ql/cashflows/fixedratecoupon.cpp \
ql/cashflows/floatingratecoupon.cpp \
ql/cashflows/iborcoupon.cpp \
ql/cashflows/indexedcashflow.cpp \
ql/cashflows/inflationcoupon.cpp \
ql/cashflows/inflationcouponpricer.cpp \
ql/cashflows/overnightindexedcoupon.cpp \
ql/cashflows/rangeaccrual.cpp \
ql/cashflows/replication.cpp \
ql/cashflows/simplecashflow.cpp \
ql/cashflows/timebasket.cpp \
ql/cashflows/yoyinflationcoupon.cpp \
ql/currencies/exchangeratemanager.cpp \
ql/currency.cpp \
ql/discretizedasset.cpp \
ql/errors.cpp \
ql/event.cpp \
ql/exchangerate.cpp \
ql/exercise.cpp \
ql/experimental/amortizingbonds/amortizingcmsratebond.cpp \
ql/experimental/amortizingbonds/amortizingfixedratebond.cpp \
ql/experimental/amortizingbonds/amortizingfloatingratebond.cpp \
ql/experimental/barrieroption/perturbativebarrieroptionengine.cpp \
ql/experimental/callablebonds/blackcallablebondengine.cpp \
ql/experimental/callablebonds/callablebond.cpp \
ql/experimental/callablebonds/callablebondconstantvol.cpp \
ql/experimental/callablebonds/callablebondvolstructure.cpp \
ql/experimental/callablebonds/discretizedcallablefixedratebond.cpp \
ql/experimental/callablebonds/treecallablebondengine.cpp \
ql/experimental/commodities/commodity.cpp \
ql/experimental/commodities/commoditycashflow.cpp \
ql/experimental/commodities/commoditycurve.cpp \
ql/experimental/commodities/commodityindex.cpp \
ql/experimental/commodities/commoditypricinghelpers.cpp \
ql/experimental/commodities/commoditysettings.cpp \
ql/experimental/commodities/commoditytype.cpp \
ql/experimental/commodities/commodityunitcost.cpp \
ql/experimental/commodities/dateinterval.cpp \
ql/experimental/commodities/energybasisswap.cpp \
ql/experimental/commodities/energycommodity.cpp \
ql/experimental/commodities/energyfuture.cpp \
ql/experimental/commodities/energyswap.cpp \
ql/experimental/commodities/energyvanillaswap.cpp \
ql/experimental/commodities/paymentterm.cpp \
ql/experimental/commodities/quantity.cpp \
ql/experimental/commodities/unitofmeasure.cpp \
ql/experimental/commodities/unitofmeasureconversion.cpp \
ql/experimental/commodities/unitofmeasureconversionmanager.cpp \
ql/experimental/compoundoption/analyticcompoundoptionengine.cpp \
ql/experimental/compoundoption/compoundoption.cpp \
ql/experimental/convertiblebonds/convertiblebond.cpp \
ql/experimental/convertiblebonds/discretizedconvertible.cpp \
ql/experimental/coupons/proxyibor.cpp \
ql/experimental/coupons/quantocouponpricer.cpp \
ql/experimental/coupons/subperiodcoupons.cpp \
ql/experimental/credit/basket.cpp \
ql/experimental/credit/blackcdsoptionengine.cpp \
ql/experimental/credit/cdo.cpp \
ql/experimental/credit/cdsoption.cpp \
ql/experimental/credit/defaultevent.cpp \
ql/experimental/credit/defaultprobabilitykey.cpp \
ql/experimental/credit/defaulttype.cpp \
ql/experimental/credit/distribution.cpp \
ql/experimental/credit/issuer.cpp \
ql/experimental/credit/lossdistribution.cpp \
ql/experimental/credit/nthtodefault.cpp \
ql/experimental/credit/onefactorcopula.cpp \
ql/experimental/credit/onefactorgaussiancopula.cpp \
ql/experimental/credit/onefactorstudentcopula.cpp \
ql/experimental/credit/pool.cpp \
ql/experimental/credit/randomdefaultmodel.cpp \
ql/experimental/credit/recoveryratemodel.cpp \
ql/experimental/credit/recoveryratequote.cpp \
ql/experimental/credit/riskyassetswap.cpp \
ql/experimental/credit/riskyassetswapoption.cpp \
ql/experimental/credit/riskybond.cpp \
ql/experimental/credit/syntheticcdo.cpp \
ql/experimental/credit/syntheticcdoengines.cpp \
ql/experimental/exoticoptions/analyticamericanmargrabeengine.cpp \
ql/experimental/exoticoptions/analyticeuropeanmargrabeengine.cpp \
ql/experimental/exoticoptions/analyticsimplechooserengine.cpp \
ql/experimental/exoticoptions/analytictwoassetbarrierengine.cpp \
ql/experimental/exoticoptions/analyticwriterextensibleoptionengine.cpp \
ql/experimental/exoticoptions/continuousarithmeticasianlevyengine.cpp \
ql/experimental/exoticoptions/everestoption.cpp \
ql/experimental/exoticoptions/himalayaoption.cpp \
ql/experimental/exoticoptions/kirkspreadoptionengine.cpp \
ql/experimental/exoticoptions/margrabeoption.cpp \
ql/experimental/exoticoptions/mceverestengine.cpp \
ql/experimental/exoticoptions/mchimalayaengine.cpp \
ql/experimental/exoticoptions/mcpagodaengine.cpp \
ql/experimental/exoticoptions/pagodaoption.cpp \
ql/experimental/exoticoptions/simplechooseroption.cpp \
ql/experimental/exoticoptions/twoassetbarrieroption.cpp \
ql/experimental/exoticoptions/writerextensibleoption.cpp \
ql/experimental/finitedifferences/dynprogvppintrinsicvalueengine.cpp \
ql/experimental/finitedifferences/fdextoujumpvanillaengine.cpp \
ql/experimental/finitedifferences/fdklugeextouspreadengine.cpp \
ql/experimental/finitedifferences/fdmblackscholesfwdop.cpp \
ql/experimental/finitedifferences/fdmextendedornsteinuhlenbeckop.cpp \
ql/experimental/finitedifferences/fdmextoujumpop.cpp \
ql/experimental/finitedifferences/fdmextoujumpsolver.cpp \
ql/experimental/finitedifferences/fdmhestonfwdop.cpp \
ql/experimental/finitedifferences/fdmklugeextouop.cpp \
ql/experimental/finitedifferences/fdmsquarerootfwdop.cpp \
ql/experimental/finitedifferences/fdmvppstartlimitstepcondition.cpp \
ql/experimental/finitedifferences/fdmvppstepcondition.cpp \
ql/experimental/finitedifferences/fdmvppstepconditionfactory.cpp \
ql/experimental/finitedifferences/fdsimpleextoujumpswingengine.cpp \
ql/experimental/finitedifferences/fdsimpleextoustorageengine.cpp \
ql/experimental/finitedifferences/fdsimpleklugeextouvppengine.cpp \
ql/experimental/finitedifferences/glued1dmesher.cpp \
ql/experimental/finitedifferences/vanillavppoption.cpp \
ql/experimental/fx/blackdeltacalculator.cpp \
ql/experimental/fx/deltavolquote.cpp \
ql/experimental/inflation/cpicapfloorengines.cpp \
ql/experimental/inflation/cpicapfloortermpricesurface.cpp \
ql/experimental/inflation/yoycapfloortermpricesurface.cpp \
ql/experimental/inflation/yoyoptionlethelpers.cpp \
ql/experimental/lattices/extendedbinomialtree.cpp \
ql/experimental/math/expm.cpp \
ql/experimental/math/zigguratrng.cpp \
ql/experimental/mcbasket/adaptedpathpayoff.cpp \
ql/experimental/mcbasket/longstaffschwartzmultipathpricer.cpp \
ql/experimental/mcbasket/mcpathbasketengine.cpp \
ql/experimental/mcbasket/pathmultiassetoption.cpp \
ql/experimental/models/atmadjustedsmilesection.cpp \
ql/experimental/models/atmsmilesection.cpp \
ql/experimental/models/kahalesmilesection.cpp \
ql/experimental/models/markovfunctional.cpp \
ql/experimental/models/markovfunctionalcapfloorengine.cpp \
ql/experimental/models/markovfunctionalswaptionengine.cpp \
ql/experimental/models/mfstateprocess.cpp \
ql/experimental/models/smilesectionutils.cpp \
ql/experimental/processes/extendedblackscholesprocess.cpp \
ql/experimental/processes/extendedornsteinuhlenbeckprocess.cpp \
ql/experimental/processes/extouwithjumpsprocess.cpp \
ql/experimental/processes/gemanroncoroniprocess.cpp \
ql/experimental/processes/klugeextouprocess.cpp \
ql/experimental/processes/vegastressedblackscholesprocess.cpp \
ql/experimental/risk/sensitivityanalysis.cpp \
ql/experimental/shortrate/generalizedhullwhite.cpp \
ql/experimental/shortrate/generalizedornsteinuhlenbeckprocess.cpp \
ql/experimental/variancegamma/analyticvariancegammaengine.cpp \
ql/experimental/variancegamma/fftengine.cpp \
ql/experimental/variancegamma/fftvanillaengine.cpp \
ql/experimental/variancegamma/fftvariancegammaengine.cpp \
ql/experimental/variancegamma/variancegammamodel.cpp \
ql/experimental/variancegamma/variancegammaprocess.cpp \
ql/experimental/varianceoption/integralhestonvarianceoptionengine.cpp \
ql/experimental/varianceoption/varianceoption.cpp \
ql/experimental/volatility/abcdatmvolcurve.cpp \
ql/experimental/volatility/blackatmvolcurve.cpp \
ql/experimental/volatility/blackvolsurface.cpp \
ql/experimental/volatility/equityfxvolsurface.cpp \
ql/experimental/volatility/extendedblackvariancecurve.cpp \
ql/experimental/volatility/extendedblackvariancesurface.cpp \
ql/experimental/volatility/interestratevolsurface.cpp \
ql/experimental/volatility/sabrvolsurface.cpp \
ql/experimental/volatility/volcube.cpp \
ql/index.cpp \
ql/indexes/bmaindex.cpp \
ql/indexes/ibor/eonia.cpp \
ql/indexes/ibor/euribor.cpp \
ql/indexes/ibor/eurlibor.cpp \
ql/indexes/ibor/libor.cpp \
ql/indexes/ibor/sonia.cpp \
ql/indexes/iborindex.cpp \
ql/indexes/indexmanager.cpp \
ql/indexes/inflationindex.cpp \
ql/indexes/interestrateindex.cpp \
ql/indexes/region.cpp \
ql/indexes/swap/chfliborswap.cpp \
ql/indexes/swap/euriborswap.cpp \
ql/indexes/swap/eurliborswap.cpp \
ql/indexes/swap/gbpliborswap.cpp \
ql/indexes/swap/jpyliborswap.cpp \
ql/indexes/swap/usdliborswap.cpp \
ql/indexes/swapindex.cpp \
ql/instruments/asianoption.cpp \
ql/instruments/assetswap.cpp \
ql/instruments/averagetype.cpp \
ql/instruments/barrieroption.cpp \
ql/instruments/barriertype.cpp \
ql/instruments/basketoption.cpp \
ql/instruments/bmaswap.cpp \
ql/instruments/bond.cpp \
ql/instruments/bonds/btp.cpp \
ql/instruments/bonds/cmsratebond.cpp \
ql/instruments/bonds/cpibond.cpp \
ql/instruments/bonds/fixedratebond.cpp \
ql/instruments/bonds/floatingratebond.cpp \
ql/instruments/bonds/zerocouponbond.cpp \
ql/instruments/capfloor.cpp \
ql/instruments/claim.cpp \
ql/instruments/cliquetoption.cpp \
ql/instruments/compositeinstrument.cpp \
ql/instruments/cpicapfloor.cpp \
ql/instruments/cpiswap.cpp \
ql/instruments/creditdefaultswap.cpp \
ql/instruments/dividendbarrieroption.cpp \
ql/instruments/dividendvanillaoption.cpp \
ql/instruments/europeanoption.cpp \
ql/instruments/fixedratebondforward.cpp \
ql/instruments/forward.cpp \
ql/instruments/forwardrateagreement.cpp \
ql/instruments/forwardvanillaoption.cpp \
ql/instruments/impliedvolatility.cpp \
ql/instruments/inflationcapfloor.cpp \
ql/instruments/lookbackoption.cpp \
ql/instruments/makecapfloor.cpp \
ql/instruments/makecms.cpp \
ql/instruments/makeois.cpp \
ql/instruments/makeswaption.cpp \
ql/instruments/makevanillaswap.cpp \
ql/instruments/makeyoyinflationcapfloor.cpp \
ql/instruments/multiassetoption.cpp \
ql/instruments/oneassetoption.cpp \
ql/instruments/overnightindexedswap.cpp \
ql/instruments/payoffs.cpp \
ql/instruments/quantobarrieroption.cpp \
ql/instruments/quantoforwardvanillaoption.cpp \
ql/instruments/quantovanillaoption.cpp \
ql/instruments/stickyratchet.cpp \
ql/instruments/stock.cpp \
ql/instruments/swap.cpp \
ql/instruments/swaption.cpp \
ql/instruments/vanillaoption.cpp \
ql/instruments/vanillaswap.cpp \
ql/instruments/vanillaswingoption.cpp \
ql/instruments/varianceswap.cpp \
ql/instruments/yearonyearinflationswap.cpp \
ql/instruments/zerocouponinflationswap.cpp \
ql/interestrate.cpp \
ql/legacy/libormarketmodels/lfmcovarparam.cpp \
ql/legacy/libormarketmodels/lfmcovarproxy.cpp \
ql/legacy/libormarketmodels/lfmhullwhiteparam.cpp \
ql/legacy/libormarketmodels/lfmprocess.cpp \
ql/legacy/libormarketmodels/lfmswaptionengine.cpp \
ql/legacy/libormarketmodels/liborforwardmodel.cpp \
ql/legacy/libormarketmodels/lmcorrmodel.cpp \
ql/legacy/libormarketmodels/lmexpcorrmodel.cpp \
ql/legacy/libormarketmodels/lmextlinexpvolmodel.cpp \
ql/legacy/libormarketmodels/lmfixedvolmodel.cpp \
ql/legacy/libormarketmodels/lmlinexpcorrmodel.cpp \
ql/legacy/libormarketmodels/lmlinexpvolmodel.cpp \
ql/legacy/libormarketmodels/lmvolmodel.cpp \
ql/math/bernsteinpolynomial.cpp \
ql/math/beta.cpp \
ql/math/bspline.cpp \
ql/math/copulas/alimikhailhaqcopula.cpp \
ql/math/copulas/claytoncopula.cpp \
ql/math/copulas/farliegumbelmorgensterncopula.cpp \
ql/math/copulas/frankcopula.cpp \
ql/math/copulas/galamboscopula.cpp \
ql/math/copulas/gaussiancopula.cpp \
ql/math/copulas/gumbelcopula.cpp \
ql/math/copulas/huslerreisscopula.cpp \
ql/math/copulas/independentcopula.cpp \
ql/math/copulas/marshallolkincopula.cpp \
ql/math/copulas/maxcopula.cpp \
ql/math/copulas/mincopula.cpp \
ql/math/copulas/plackettcopula.cpp \
ql/math/distributions/bivariatenormaldistribution.cpp \
ql/math/distributions/chisquaredistribution.cpp \
ql/math/distributions/gammadistribution.cpp \
ql/math/distributions/normaldistribution.cpp \
ql/math/distributions/studenttdistribution.cpp \
ql/math/errorfunction.cpp \
ql/math/factorial.cpp \
ql/math/incompletegamma.cpp \
ql/math/integrals/gaussianorthogonalpolynomial.cpp \
ql/math/integrals/gaussianquadratures.cpp \
ql/math/integrals/gausslobattointegral.cpp \
ql/math/integrals/integral.cpp \
ql/math/integrals/kronrodintegral.cpp \
ql/math/integrals/segmentintegral.cpp \
ql/math/matrix.cpp \
ql/math/matrixutilities/basisincompleteordered.cpp \
ql/math/matrixutilities/bicgstab.cpp \
ql/math/matrixutilities/choleskydecomposition.cpp \
ql/math/matrixutilities/factorreduction.cpp \
ql/math/matrixutilities/getcovariance.cpp \
ql/math/matrixutilities/pseudosqrt.cpp \
ql/math/matrixutilities/qrdecomposition.cpp \
ql/math/matrixutilities/sparseilupreconditioner.cpp \
ql/math/matrixutilities/svd.cpp \
ql/math/matrixutilities/symmetricschurdecomposition.cpp \
ql/math/matrixutilities/tapcorrelations.cpp \
ql/math/matrixutilities/tqreigendecomposition.cpp \
ql/math/optimization/armijo.cpp \
ql/math/optimization/bfgs.cpp \
ql/math/optimization/conjugategradient.cpp \
ql/math/optimization/constraint.cpp \
ql/math/optimization/differentialevolution.cpp \
ql/math/optimization/endcriteria.cpp \
ql/math/optimization/leastsquare.cpp \
ql/math/optimization/levenbergmarquardt.cpp \
ql/math/optimization/linesearch.cpp \
ql/math/optimization/linesearchbasedmethod.cpp \
ql/math/optimization/lmdif.cpp \
ql/math/optimization/projectedcostfunction.cpp \
ql/math/optimization/simplex.cpp \
ql/math/optimization/spherecylinder.cpp \
ql/math/optimization/steepestdescent.cpp \
ql/math/primenumbers.cpp \
ql/math/quadratic.cpp \
ql/math/randomnumbers/faurersg.cpp \
ql/math/randomnumbers/haltonrsg.cpp \
ql/math/randomnumbers/knuthuniformrng.cpp \
ql/math/randomnumbers/latticersg.cpp \
ql/math/randomnumbers/latticerules.cpp \
ql/math/randomnumbers/lecuyeruniformrng.cpp \
ql/math/randomnumbers/mt19937uniformrng.cpp \
ql/math/randomnumbers/seedgenerator.cpp \
ql/math/randomnumbers/sobolbrownianbridgersg.cpp \
ql/math/randomnumbers/sobolrsg.cpp \
ql/math/richardsonextrapolation.cpp \
ql/math/rounding.cpp \
ql/math/sampledcurve.cpp \
ql/math/statistics/discrepancystatistics.cpp \
ql/math/statistics/generalstatistics.cpp \
ql/math/statistics/histogram.cpp \
ql/math/statistics/incrementalstatistics.cpp \
ql/math/surface.cpp \
ql/methods/finitedifferences/boundarycondition.cpp \
ql/methods/finitedifferences/bsmoperator.cpp \
ql/methods/finitedifferences/meshers/concentrating1dmesher.cpp \
ql/methods/finitedifferences/meshers/exponentialjump1dmesher.cpp \
ql/methods/finitedifferences/meshers/fdmblackscholesmesher.cpp \
ql/methods/finitedifferences/meshers/fdmblackscholesmultistrikemesher.cpp \
ql/methods/finitedifferences/meshers/fdmhestonvariancemesher.cpp \
ql/methods/finitedifferences/meshers/fdmmeshercomposite.cpp \
ql/methods/finitedifferences/meshers/fdmsimpleprocess1dmesher.cpp \
ql/methods/finitedifferences/meshers/uniformgridmesher.cpp \
ql/methods/finitedifferences/operators/fdm2dblackscholesop.cpp \
ql/methods/finitedifferences/operators/fdmbatesop.cpp \
ql/methods/finitedifferences/operators/fdmblackscholesop.cpp \
ql/methods/finitedifferences/operators/fdmg2op.cpp \
ql/methods/finitedifferences/operators/fdmhestonhullwhiteop.cpp \
ql/methods/finitedifferences/operators/fdmhestonop.cpp \
ql/methods/finitedifferences/operators/fdmhullwhiteop.cpp \
ql/methods/finitedifferences/operators/fdmlinearoplayout.cpp \
ql/methods/finitedifferences/operators/firstderivativeop.cpp \
ql/methods/finitedifferences/operators/ninepointlinearop.cpp \
ql/methods/finitedifferences/operators/secondderivativeop.cpp \
ql/methods/finitedifferences/operators/secondordermixedderivativeop.cpp \
ql/methods/finitedifferences/operators/triplebandlinearop.cpp \
ql/methods/finitedifferences/schemes/craigsneydscheme.cpp \
ql/methods/finitedifferences/schemes/douglasscheme.cpp \
ql/methods/finitedifferences/schemes/expliciteulerscheme.cpp \
ql/methods/finitedifferences/schemes/hundsdorferscheme.cpp \
ql/methods/finitedifferences/schemes/impliciteulerscheme.cpp \
ql/methods/finitedifferences/schemes/modifiedcraigsneydscheme.cpp \
ql/methods/finitedifferences/solvers/fdm1dimsolver.cpp \
ql/methods/finitedifferences/solvers/fdm2dblackscholessolver.cpp \
ql/methods/finitedifferences/solvers/fdm2dimsolver.cpp \
ql/methods/finitedifferences/solvers/fdm3dimsolver.cpp \
ql/methods/finitedifferences/solvers/fdmbackwardsolver.cpp \
ql/methods/finitedifferences/solvers/fdmbatessolver.cpp \
ql/methods/finitedifferences/solvers/fdmblackscholessolver.cpp \
ql/methods/finitedifferences/solvers/fdmg2solver.cpp \
ql/methods/finitedifferences/solvers/fdmhestonhullwhitesolver.cpp \
ql/methods/finitedifferences/solvers/fdmhestonsolver.cpp \
ql/methods/finitedifferences/solvers/fdmhullwhitesolver.cpp \
ql/methods/finitedifferences/solvers/fdmsimple2dbssolver.cpp \
ql/methods/finitedifferences/stepconditions/fdmamericanstepcondition.cpp \
ql/methods/finitedifferences/stepconditions/fdmarithmeticaveragecondition.cpp \
ql/methods/finitedifferences/stepconditions/fdmbermudanstepcondition.cpp \
ql/methods/finitedifferences/stepconditions/fdmsimplestoragecondition.cpp \
ql/methods/finitedifferences/stepconditions/fdmsimpleswingcondition.cpp \
ql/methods/finitedifferences/stepconditions/fdmsnapshotcondition.cpp \
ql/methods/finitedifferences/stepconditions/fdmstepconditioncomposite.cpp \
ql/methods/finitedifferences/tridiagonaloperator.cpp \
ql/methods/finitedifferences/utilities/fdmaffinemodelswapinnervalue.cpp \
ql/methods/finitedifferences/utilities/fdmaffinemodeltermstructure.cpp \
ql/methods/finitedifferences/utilities/fdmdirichletboundary.cpp \
ql/methods/finitedifferences/utilities/fdmdividendhandler.cpp \
ql/methods/finitedifferences/utilities/fdmindicesonboundary.cpp \
ql/methods/finitedifferences/utilities/fdminnervaluecalculator.cpp \
ql/methods/finitedifferences/utilities/fdmquantohelper.cpp \
ql/methods/finitedifferences/utilities/fdmtimedepdirichletboundary.cpp \
ql/methods/lattices/binomialtree.cpp \
ql/methods/lattices/trinomialtree.cpp \
ql/methods/montecarlo/brownianbridge.cpp \
ql/methods/montecarlo/genericlsregression.cpp \
ql/methods/montecarlo/lsmbasissystem.cpp \
ql/methods/montecarlo/parametricexercise.cpp \
ql/models/calibrationhelper.cpp \
ql/models/equity/batesmodel.cpp \
ql/models/equity/gjrgarchmodel.cpp \
ql/models/equity/hestonmodel.cpp \
ql/models/equity/hestonmodelhelper.cpp \
ql/models/equity/piecewisetimedependenthestonmodel.cpp \
ql/models/marketmodels/accountingengine.cpp \
ql/models/marketmodels/browniangenerators/mtbrowniangenerator.cpp \
ql/models/marketmodels/browniangenerators/sobolbrowniangenerator.cpp \
ql/models/marketmodels/callability/bermudanswaptionexercisevalue.cpp \
ql/models/marketmodels/callability/collectnodedata.cpp \
ql/models/marketmodels/callability/lsstrategy.cpp \
ql/models/marketmodels/callability/nothingexercisevalue.cpp \
ql/models/marketmodels/callability/parametricexerciseadapter.cpp \
ql/models/marketmodels/callability/swapbasissystem.cpp \
ql/models/marketmodels/callability/swapforwardbasissystem.cpp \
ql/models/marketmodels/callability/swapratetrigger.cpp \
ql/models/marketmodels/callability/triggeredswapexercise.cpp \
ql/models/marketmodels/callability/upperboundengine.cpp \
ql/models/marketmodels/correlations/cotswapfromfwdcorrelation.cpp \
ql/models/marketmodels/correlations/expcorrelations.cpp \
ql/models/marketmodels/correlations/timehomogeneousforwardcorrelation.cpp \
ql/models/marketmodels/curvestate.cpp \
ql/models/marketmodels/curvestates/cmswapcurvestate.cpp \
ql/models/marketmodels/curvestates/coterminalswapcurvestate.cpp \
ql/models/marketmodels/curvestates/lmmcurvestate.cpp \
ql/models/marketmodels/discounter.cpp \
ql/models/marketmodels/driftcomputation/cmsmmdriftcalculator.cpp \
ql/models/marketmodels/driftcomputation/lmmdriftcalculator.cpp \
ql/models/marketmodels/driftcomputation/lmmnormaldriftcalculator.cpp \
ql/models/marketmodels/driftcomputation/smmdriftcalculator.cpp \
ql/models/marketmodels/evolutiondescription.cpp \
ql/models/marketmodels/evolvers/lognormalcmswapratepc.cpp \
ql/models/marketmodels/evolvers/lognormalcotswapratepc.cpp \
ql/models/marketmodels/evolvers/lognormalfwdrateballand.cpp \
ql/models/marketmodels/evolvers/lognormalfwdrateeuler.cpp \
ql/models/marketmodels/evolvers/lognormalfwdrateeulerconstrained.cpp \
ql/models/marketmodels/evolvers/lognormalfwdrateiballand.cpp \
ql/models/marketmodels/evolvers/lognormalfwdrateipc.cpp \
ql/models/marketmodels/evolvers/lognormalfwdratepc.cpp \
ql/models/marketmodels/evolvers/marketmodelvolprocess.cpp \
ql/models/marketmodels/evolvers/normalfwdratepc.cpp \
ql/models/marketmodels/evolvers/svddfwdratepc.cpp \
ql/models/marketmodels/evolvers/volprocesses/squarerootandersen.cpp \
ql/models/marketmodels/forwardforwardmappings.cpp \
ql/models/marketmodels/historicalratesanalysis.cpp \
ql/models/marketmodels/marketmodel.cpp \
ql/models/marketmodels/marketmodeldifferences.cpp \
ql/models/marketmodels/models/abcdvol.cpp \
ql/models/marketmodels/models/alphafinder.cpp \
ql/models/marketmodels/models/alphaformconcrete.cpp \
ql/models/marketmodels/models/capletcoterminalalphacalibration.cpp \
ql/models/marketmodels/models/capletcoterminalmaxhomogeneity.cpp \
ql/models/marketmodels/models/capletcoterminalperiodic.cpp \
ql/models/marketmodels/models/capletcoterminalswaptioncalibration.cpp \
ql/models/marketmodels/models/cotswaptofwdadapter.cpp \
ql/models/marketmodels/models/ctsmmcapletcalibration.cpp \
ql/models/marketmodels/models/flatvol.cpp \
ql/models/marketmodels/models/fwdperiodadapter.cpp \
ql/models/marketmodels/models/fwdtocotswapadapter.cpp \
ql/models/marketmodels/models/piecewiseconstantabcdvariance.cpp \
ql/models/marketmodels/models/piecewiseconstantvariance.cpp \
ql/models/marketmodels/models/pseudorootfacade.cpp \
ql/models/marketmodels/models/volatilityinterpolationspecifier.cpp \
ql/models/marketmodels/models/volatilityinterpolationspecifierabcd.cpp \
ql/models/marketmodels/pathwiseaccountingengine.cpp \
ql/models/marketmodels/pathwisediscounter.cpp \
ql/models/marketmodels/pathwisegreeks/bumpinstrumentjacobian.cpp \
ql/models/marketmodels/pathwisegreeks/ratepseudorootjacobian.cpp \
ql/models/marketmodels/pathwisegreeks/swaptionpseudojacobian.cpp \
ql/models/marketmodels/pathwisegreeks/vegabumpcluster.cpp \
ql/models/marketmodels/products/compositeproduct.cpp \
ql/models/marketmodels/products/multiproductcomposite.cpp \
ql/models/marketmodels/products/multiproductmultistep.cpp \
ql/models/marketmodels/products/multiproductonestep.cpp \
ql/models/marketmodels/products/multistep/callspecifiedmultiproduct.cpp \
ql/models/marketmodels/products/multistep/cashrebate.cpp \
ql/models/marketmodels/products/multistep/exerciseadapter.cpp \
ql/models/marketmodels/products/multistep/multistepcoinitialswaps.cpp \
ql/models/marketmodels/products/multistep/multistepcoterminalswaps.cpp \
ql/models/marketmodels/products/multistep/multistepcoterminalswaptions.cpp \
ql/models/marketmodels/products/multistep/multistepforwards.cpp \
ql/models/marketmodels/products/multistep/multistepinversefloater.cpp \
ql/models/marketmodels/products/multistep/multistepnothing.cpp \
ql/models/marketmodels/products/multistep/multistepoptionlets.cpp \
ql/models/marketmodels/products/multistep/multisteppathwisewrapper.cpp \
ql/models/marketmodels/products/multistep/multistepperiodcapletswaptions.cpp \
ql/models/marketmodels/products/multistep/multistepratchet.cpp \
ql/models/marketmodels/products/multistep/multistepswap.cpp \
ql/models/marketmodels/products/multistep/multistepswaption.cpp \
ql/models/marketmodels/products/multistep/multisteptarn.cpp \
ql/models/marketmodels/products/onestep/onestepcoinitialswaps.cpp \
ql/models/marketmodels/products/onestep/onestepcoterminalswaps.cpp \
ql/models/marketmodels/products/onestep/onestepforwards.cpp \
ql/models/marketmodels/products/onestep/onestepoptionlets.cpp \
ql/models/marketmodels/products/pathwise/pathwiseproductcallspecified.cpp \
ql/models/marketmodels/products/pathwise/pathwiseproductcaplet.cpp \
ql/models/marketmodels/products/pathwise/pathwiseproductcashrebate.cpp \
ql/models/marketmodels/products/pathwise/pathwiseproductinversefloater.cpp \
ql/models/marketmodels/products/pathwise/pathwiseproductswap.cpp \
ql/models/marketmodels/products/pathwise/pathwiseproductswaption.cpp \
ql/models/marketmodels/products/singleproductcomposite.cpp \
ql/models/marketmodels/proxygreekengine.cpp \
ql/models/marketmodels/swapforwardmappings.cpp \
ql/models/marketmodels/utilities.cpp \
ql/models/model.cpp \
ql/models/shortrate/calibrationhelpers/caphelper.cpp \
ql/models/shortrate/calibrationhelpers/swaptionhelper.cpp \
ql/models/shortrate/onefactormodel.cpp \
ql/models/shortrate/onefactormodels/blackkarasinski.cpp \
ql/models/shortrate/onefactormodels/coxingersollross.cpp \
ql/models/shortrate/onefactormodels/extendedcoxingersollross.cpp \
ql/models/shortrate/onefactormodels/hullwhite.cpp \
ql/models/shortrate/onefactormodels/vasicek.cpp \
ql/models/shortrate/twofactormodel.cpp \
ql/models/shortrate/twofactormodels/g2.cpp \
ql/models/volatility/constantestimator.cpp \
ql/models/volatility/garch.cpp \
ql/money.cpp \
ql/position.cpp \
ql/prices.cpp \
ql/pricingengines/americanpayoffatexpiry.cpp \
ql/pricingengines/americanpayoffathit.cpp \
ql/pricingengines/asian/analytic_cont_geom_av_price.cpp \
ql/pricingengines/asian/analytic_discr_geom_av_price.cpp \
ql/pricingengines/asian/analytic_discr_geom_av_strike.cpp \
ql/pricingengines/asian/fdblackscholesasianengine.cpp \
ql/pricingengines/asian/mc_discr_arith_av_price.cpp \
ql/pricingengines/asian/mc_discr_arith_av_strike.cpp \
ql/pricingengines/asian/mc_discr_geom_av_price.cpp \
ql/pricingengines/barrier/analyticbarrierengine.cpp \
ql/pricingengines/barrier/fdblackscholesbarrierengine.cpp \
ql/pricingengines/barrier/fdblackscholesrebateengine.cpp \
ql/pricingengines/barrier/fdhestonbarrierengine.cpp \
ql/pricingengines/barrier/fdhestonrebateengine.cpp \
ql/pricingengines/barrier/mcbarrierengine.cpp \
ql/pricingengines/basket/fd2dblackscholesvanillaengine.cpp \
ql/pricingengines/basket/kirkengine.cpp \
ql/pricingengines/basket/mcamericanbasketengine.cpp \
ql/pricingengines/basket/mceuropeanbasketengine.cpp \
ql/pricingengines/basket/stulzengine.cpp \
ql/pricingengines/blackcalculator.cpp \
ql/pricingengines/blackformula.cpp \
ql/pricingengines/blackscholescalculator.cpp \
ql/pricingengines/bond/bondfunctions.cpp \
ql/pricingengines/bond/discountingbondengine.cpp \
ql/pricingengines/capfloor/analyticcapfloorengine.cpp \
ql/pricingengines/capfloor/blackcapfloorengine.cpp \
ql/pricingengines/capfloor/discretizedcapfloor.cpp \
ql/pricingengines/capfloor/mchullwhiteengine.cpp \
ql/pricingengines/capfloor/treecapfloorengine.cpp \
ql/pricingengines/cliquet/analyticcliquetengine.cpp \
ql/pricingengines/cliquet/analyticperformanceengine.cpp \
ql/pricingengines/cliquet/mcperformanceengine.cpp \
ql/pricingengines/credit/integralcdsengine.cpp \
ql/pricingengines/credit/midpointcdsengine.cpp \
ql/pricingengines/greeks.cpp \
ql/pricingengines/inflation/inflationcapfloorengines.cpp \
ql/pricingengines/lookback/analyticcontinuousfixedlookback.cpp \
ql/pricingengines/lookback/analyticcontinuousfloatinglookback.cpp \
ql/pricingengines/swap/discountingswapengine.cpp \
ql/pricingengines/swap/discretizedswap.cpp \
ql/pricingengines/swap/treeswapengine.cpp \
ql/pricingengines/swaption/blackswaptionengine.cpp \
ql/pricingengines/swaption/discretizedswaption.cpp \
ql/pricingengines/swaption/fdg2swaptionengine.cpp \
ql/pricingengines/swaption/fdhullwhiteswaptionengine.cpp \
ql/pricingengines/swaption/jamshidianswaptionengine.cpp \
ql/pricingengines/swaption/treeswaptionengine.cpp \
ql/pricingengines/vanilla/analyticbsmhullwhiteengine.cpp \
ql/pricingengines/vanilla/analyticdigitalamericanengine.cpp \
ql/pricingengines/vanilla/analyticdividendeuropeanengine.cpp \
ql/pricingengines/vanilla/analyticeuropeanengine.cpp \
ql/pricingengines/vanilla/analyticgjrgarchengine.cpp \
ql/pricingengines/vanilla/analytich1hwengine.cpp \
ql/pricingengines/vanilla/analytichestonengine.cpp \
ql/pricingengines/vanilla/analytichestonhullwhiteengine.cpp \
ql/pricingengines/vanilla/analyticptdhestonengine.cpp \
ql/pricingengines/vanilla/baroneadesiwhaleyengine.cpp \
ql/pricingengines/vanilla/batesengine.cpp \
ql/pricingengines/vanilla/bjerksundstenslandengine.cpp \
ql/pricingengines/vanilla/discretizedvanillaoption.cpp \
ql/pricingengines/vanilla/fdbatesvanillaengine.cpp \
ql/pricingengines/vanilla/fdblackscholesvanillaengine.cpp \
ql/pricingengines/vanilla/fdhestonhullwhitevanillaengine.cpp \
ql/pricingengines/vanilla/fdhestonvanillaengine.cpp \
ql/pricingengines/vanilla/fdsimplebsswingengine.cpp \
ql/pricingengines/vanilla/fdvanillaengine.cpp \
ql/pricingengines/vanilla/integralengine.cpp \
ql/pricingengines/vanilla/jumpdiffusionengine.cpp \
ql/pricingengines/vanilla/juquadraticengine.cpp \
ql/pricingengines/vanilla/mcamericanengine.cpp \
ql/pricingengines/vanilla/mcdigitalengine.cpp \
ql/pricingengines/vanilla/mchestonhullwhiteengine.cpp \
ql/processes/batesprocess.cpp \
ql/processes/blackscholesprocess.cpp \
ql/processes/endeulerdiscretization.cpp \
ql/processes/eulerdiscretization.cpp \
ql/processes/forwardmeasureprocess.cpp \
ql/processes/g2process.cpp \
ql/processes/geometricbrownianprocess.cpp \
ql/processes/gjrgarchprocess.cpp \
ql/processes/hestonprocess.cpp \
ql/processes/hullwhiteprocess.cpp \
ql/processes/hybridhestonhullwhiteprocess.cpp \
ql/processes/jointstochasticprocess.cpp \
ql/processes/merton76process.cpp \
ql/processes/ornsteinuhlenbeckprocess.cpp \
ql/processes/squarerootprocess.cpp \
ql/processes/stochasticprocessarray.cpp \
ql/quotes/eurodollarfuturesquote.cpp \
ql/quotes/forwardswapquote.cpp \
ql/quotes/forwardvaluequote.cpp \
ql/quotes/futuresconvadjustmentquote.cpp \
ql/quotes/impliedstddevquote.cpp \
ql/quotes/lastfixingquote.cpp \
ql/settings.cpp \
ql/stochasticprocess.cpp \
ql/termstructure.cpp \
ql/termstructures/credit/defaultdensitystructure.cpp \
ql/termstructures/credit/defaultprobabilityhelpers.cpp \
ql/termstructures/credit/flathazardrate.cpp \
ql/termstructures/credit/hazardratestructure.cpp \
ql/termstructures/credit/survivalprobabilitystructure.cpp \
ql/termstructures/defaulttermstructure.cpp \
ql/termstructures/inflation/inflationhelpers.cpp \
ql/termstructures/inflation/seasonality.cpp \
ql/termstructures/inflationtermstructure.cpp \
ql/termstructures/volatility/abcd.cpp \
ql/termstructures/volatility/abcdcalibration.cpp \
ql/termstructures/volatility/capfloor/capfloortermvolatilitystructure.cpp \
ql/termstructures/volatility/capfloor/capfloortermvolcurve.cpp \
ql/termstructures/volatility/capfloor/capfloortermvolsurface.cpp \
ql/termstructures/volatility/capfloor/constantcapfloortermvol.cpp \
ql/termstructures/volatility/equityfx/blackvariancecurve.cpp \
ql/termstructures/volatility/equityfx/blackvariancesurface.cpp \
ql/termstructures/volatility/equityfx/blackvoltermstructure.cpp \
ql/termstructures/volatility/equityfx/localvolsurface.cpp \
ql/termstructures/volatility/equityfx/localvoltermstructure.cpp \
ql/termstructures/volatility/flatsmilesection.cpp \
ql/termstructures/volatility/inflation/constantcpivolatility.cpp \
ql/termstructures/volatility/inflation/cpivolatilitystructure.cpp \
ql/termstructures/volatility/inflation/yoyinflationoptionletvolatilitystructure.cpp \
ql/termstructures/volatility/optionlet/constantoptionletvol.cpp \
ql/termstructures/volatility/optionlet/optionletstripper.cpp \
ql/termstructures/volatility/optionlet/optionletstripper1.cpp \
ql/termstructures/volatility/optionlet/optionletstripper2.cpp \
ql/termstructures/volatility/optionlet/optionletvolatilitystructure.cpp \
ql/termstructures/volatility/optionlet/spreadedoptionletvol.cpp \
ql/termstructures/volatility/optionlet/strippedoptionlet.cpp \
ql/termstructures/volatility/optionlet/strippedoptionletadapter.cpp \
ql/termstructures/volatility/sabr.cpp \
ql/termstructures/volatility/sabrinterpolatedsmilesection.cpp \
ql/termstructures/volatility/sabrsmilesection.cpp \
ql/termstructures/volatility/smilesection.cpp \
ql/termstructures/volatility/spreadedsmilesection.cpp \
ql/termstructures/volatility/swaption/cmsmarket.cpp \
ql/termstructures/volatility/swaption/cmsmarketcalibration.cpp \
ql/termstructures/volatility/swaption/spreadedswaptionvol.cpp \
ql/termstructures/volatility/swaption/swaptionconstantvol.cpp \
ql/termstructures/volatility/swaption/swaptionvolcube.cpp \
ql/termstructures/volatility/swaption/swaptionvolcube1.cpp \
ql/termstructures/volatility/swaption/swaptionvolcube2.cpp \
ql/termstructures/volatility/swaption/swaptionvoldiscrete.cpp \
ql/termstructures/volatility/swaption/swaptionvolmatrix.cpp \
ql/termstructures/volatility/swaption/swaptionvolstructure.cpp \
ql/termstructures/voltermstructure.cpp \
ql/termstructures/yield/bondhelpers.cpp \
ql/termstructures/yield/fittedbonddiscountcurve.cpp \
ql/termstructures/yield/flatforward.cpp \
ql/termstructures/yield/forwardstructure.cpp \
ql/termstructures/yield/nonlinearfittingmethods.cpp \
ql/termstructures/yield/oisratehelper.cpp \
ql/termstructures/yield/ratehelpers.cpp \
ql/termstructures/yield/zeroyieldstructure.cpp \
ql/termstructures/yieldtermstructure.cpp \
ql/time/businessdayconvention.cpp \
ql/time/calendar.cpp \
ql/time/calendars/argentina.cpp \
ql/time/calendars/australia.cpp \
ql/time/calendars/bespokecalendar.cpp \
ql/time/calendars/brazil.cpp \
ql/time/calendars/canada.cpp \
ql/time/calendars/china.cpp \
ql/time/calendars/czechrepublic.cpp \
ql/time/calendars/denmark.cpp \
ql/time/calendars/finland.cpp \
ql/time/calendars/germany.cpp \
ql/time/calendars/hongkong.cpp \
ql/time/calendars/hungary.cpp \
ql/time/calendars/iceland.cpp \
ql/time/calendars/india.cpp \
ql/time/calendars/indonesia.cpp \
ql/time/calendars/italy.cpp \
ql/time/calendars/japan.cpp \
ql/time/calendars/jointcalendar.cpp \
ql/time/calendars/mexico.cpp \
ql/time/calendars/newzealand.cpp \
ql/time/calendars/norway.cpp \
ql/time/calendars/poland.cpp \
ql/time/calendars/russia.cpp \
ql/time/calendars/saudiarabia.cpp \
ql/time/calendars/singapore.cpp \
ql/time/calendars/slovakia.cpp \
ql/time/calendars/southafrica.cpp \
ql/time/calendars/southkorea.cpp \
ql/time/calendars/sweden.cpp \
ql/time/calendars/switzerland.cpp \
ql/time/calendars/taiwan.cpp \
ql/time/calendars/target.cpp \
ql/time/calendars/turkey.cpp \
ql/time/calendars/ukraine.cpp \
ql/time/calendars/unitedkingdom.cpp \
ql/time/calendars/unitedstates.cpp \
ql/time/calendars/weekendsonly.cpp \
ql/time/date.cpp \
ql/time/dategenerationrule.cpp \
ql/time/daycounters/actualactual.cpp \
ql/time/daycounters/business252.cpp \
ql/time/daycounters/simpledaycounter.cpp \
ql/time/daycounters/thirty360.cpp \
ql/time/ecb.cpp \
ql/time/frequency.cpp \
ql/time/imm.cpp \
ql/time/period.cpp \
ql/time/schedule.cpp \
ql/time/timeunit.cpp \
ql/time/weekday.cpp \
ql/timegrid.cpp \
ql/utilities/dataformatters.cpp \
ql/utilities/dataparsers.cpp \
ql/utilities/tracing.cpp



HEADERS += \
ql/math/randomnumbers/primitivepolynomials.h \
ql/auto_link.hpp \
ql/cashflow.hpp \
ql/cashflows/averagebmacoupon.hpp \
ql/cashflows/capflooredcoupon.hpp \
ql/cashflows/capflooredinflationcoupon.hpp \
ql/cashflows/cashflows.hpp \
ql/cashflows/cashflowvectors.hpp \
ql/cashflows/cmscoupon.hpp \
ql/cashflows/conundrumpricer.hpp \
ql/cashflows/coupon.hpp \
ql/cashflows/couponpricer.hpp \
ql/cashflows/cpicoupon.hpp \
ql/cashflows/cpicouponpricer.hpp \
ql/cashflows/digitalcmscoupon.hpp \
ql/cashflows/digitalcoupon.hpp \
ql/cashflows/digitaliborcoupon.hpp \
ql/cashflows/dividend.hpp \
ql/cashflows/duration.hpp \
ql/cashflows/fixedratecoupon.hpp \
ql/cashflows/floatingratecoupon.hpp \
ql/cashflows/iborcoupon.hpp \
ql/cashflows/indexedcashflow.hpp \
ql/cashflows/inflationcoupon.hpp \
ql/cashflows/inflationcouponpricer.hpp \
ql/cashflows/overnightindexedcoupon.hpp \
ql/cashflows/rangeaccrual.hpp \
ql/cashflows/replication.hpp \
ql/cashflows/simplecashflow.hpp \
ql/cashflows/timebasket.hpp \
ql/cashflows/yoyinflationcoupon.hpp \
ql/compounding.hpp \
ql/config.ansi.hpp \
ql/config.hpp \
ql/config.mingw.hpp \
ql/config.msvc.hpp \
ql/config.sun.hpp \
ql/currencies/africa.hpp \
ql/currencies/america.hpp \
ql/currencies/asia.hpp \
ql/currencies/europe.hpp \
ql/currencies/exchangeratemanager.hpp \
ql/currencies/oceania.hpp \
ql/currency.hpp \
ql/default.hpp \
ql/discretizedasset.hpp \
ql/errors.hpp \
ql/event.hpp \
ql/exchangerate.hpp \
ql/exercise.hpp \
ql/experimental/amortizingbonds/amortizingcmsratebond.hpp \
ql/experimental/amortizingbonds/amortizingfixedratebond.hpp \
ql/experimental/amortizingbonds/amortizingfloatingratebond.hpp \
ql/experimental/barrieroption/perturbativebarrieroptionengine.hpp \
ql/experimental/callablebonds/blackcallablebondengine.hpp \
ql/experimental/callablebonds/callablebond.hpp \
ql/experimental/callablebonds/callablebondconstantvol.hpp \
ql/experimental/callablebonds/callablebondvolstructure.hpp \
ql/experimental/callablebonds/discretizedcallablefixedratebond.hpp \
ql/experimental/callablebonds/treecallablebondengine.hpp \
ql/experimental/commodities/commodity.hpp \
ql/experimental/commodities/commoditycashflow.hpp \
ql/experimental/commodities/commoditycurve.hpp \
ql/experimental/commodities/commodityindex.hpp \
ql/experimental/commodities/commoditypricinghelpers.hpp \
ql/experimental/commodities/commoditysettings.hpp \
ql/experimental/commodities/commoditytype.hpp \
ql/experimental/commodities/commodityunitcost.hpp \
ql/experimental/commodities/dateinterval.hpp \
ql/experimental/commodities/energybasisswap.hpp \
ql/experimental/commodities/energycommodity.hpp \
ql/experimental/commodities/energyfuture.hpp \
ql/experimental/commodities/energyswap.hpp \
ql/experimental/commodities/energyvanillaswap.hpp \
ql/experimental/commodities/exchangecontract.hpp \
ql/experimental/commodities/paymentterm.hpp \
ql/experimental/commodities/petroleumunitsofmeasure.hpp \
ql/experimental/commodities/pricingperiod.hpp \
ql/experimental/commodities/quantity.hpp \
ql/experimental/commodities/unitofmeasure.hpp \
ql/experimental/commodities/unitofmeasureconversion.hpp \
ql/experimental/commodities/unitofmeasureconversionmanager.hpp \
ql/experimental/compoundoption/analyticcompoundoptionengine.hpp \
ql/experimental/compoundoption/compoundoption.hpp \
ql/experimental/convertiblebonds/binomialconvertibleengine.hpp \
ql/experimental/convertiblebonds/convertiblebond.hpp \
ql/experimental/convertiblebonds/discretizedconvertible.hpp \
ql/experimental/convertiblebonds/tflattice.hpp \
ql/experimental/coupons/proxyibor.hpp \
ql/experimental/coupons/quantocouponpricer.hpp \
ql/experimental/coupons/subperiodcoupons.hpp \
ql/experimental/credit/basket.hpp \
ql/experimental/credit/blackcdsoptionengine.hpp \
ql/experimental/credit/cdo.hpp \
ql/experimental/credit/cdsoption.hpp \
ql/experimental/credit/defaultevent.hpp \
ql/experimental/credit/defaultprobabilitykey.hpp \
ql/experimental/credit/defaulttype.hpp \
ql/experimental/credit/distribution.hpp \
ql/experimental/credit/factorspreadedhazardratecurve.hpp \
ql/experimental/credit/issuer.hpp \
ql/experimental/credit/loss.hpp \
ql/experimental/credit/lossdistribution.hpp \
ql/experimental/credit/nthtodefault.hpp \
ql/experimental/credit/onefactorcopula.hpp \
ql/experimental/credit/onefactorgaussiancopula.hpp \
ql/experimental/credit/onefactorstudentcopula.hpp \
ql/experimental/credit/pool.hpp \
ql/experimental/credit/randomdefaultmodel.hpp \
ql/experimental/credit/recoveryratemodel.hpp \
ql/experimental/credit/recoveryratequote.hpp \
ql/experimental/credit/recursivecdoengine.hpp \
ql/experimental/credit/riskyassetswap.hpp \
ql/experimental/credit/riskyassetswapoption.hpp \
ql/experimental/credit/riskybond.hpp \
ql/experimental/credit/spreadedhazardratecurve.hpp \
ql/experimental/credit/syntheticcdo.hpp \
ql/experimental/credit/syntheticcdoengines.hpp \
ql/experimental/exoticoptions/analyticamericanmargrabeengine.hpp \
ql/experimental/exoticoptions/analyticeuropeanmargrabeengine.hpp \
ql/experimental/exoticoptions/analyticsimplechooserengine.hpp \
ql/experimental/exoticoptions/analytictwoassetbarrierengine.hpp \
ql/experimental/exoticoptions/analyticwriterextensibleoptionengine.hpp \
ql/experimental/exoticoptions/continuousarithmeticasianlevyengine.hpp \
ql/experimental/exoticoptions/everestoption.hpp \
ql/experimental/exoticoptions/himalayaoption.hpp \
ql/experimental/exoticoptions/kirkspreadoptionengine.hpp \
ql/experimental/exoticoptions/margrabeoption.hpp \
ql/experimental/exoticoptions/mceverestengine.hpp \
ql/experimental/exoticoptions/mchimalayaengine.hpp \
ql/experimental/exoticoptions/mcpagodaengine.hpp \
ql/experimental/exoticoptions/pagodaoption.hpp \
ql/experimental/exoticoptions/simplechooseroption.hpp \
ql/experimental/exoticoptions/spreadoption.hpp \
ql/experimental/exoticoptions/twoassetbarrieroption.hpp \
ql/experimental/exoticoptions/writerextensibleoption.hpp \
ql/experimental/finitedifferences/dynprogvppintrinsicvalueengine.hpp \
ql/experimental/finitedifferences/fddstartlimitstepcondition.hpp \
ql/experimental/finitedifferences/fdextoujumpvanillaengine.hpp \
ql/experimental/finitedifferences/fdklugeextouspreadengine.hpp \
ql/experimental/finitedifferences/fdmblackscholesfwdop.hpp \
ql/experimental/finitedifferences/fdmexpextouinnervaluecalculator.hpp \
ql/experimental/finitedifferences/fdmextendedornsteinuhlenbeckop.hpp \
ql/experimental/finitedifferences/fdmextoujumpmodelinnervalue.hpp \
ql/experimental/finitedifferences/fdmextoujumpop.hpp \
ql/experimental/finitedifferences/fdmextoujumpsolver.hpp \
ql/experimental/finitedifferences/fdmhestonfwdop.hpp \
ql/experimental/finitedifferences/fdmklugeextouop.hpp \
ql/experimental/finitedifferences/fdmklugeextousolver.hpp \
ql/experimental/finitedifferences/fdmsimple2dextousolver.hpp \
ql/experimental/finitedifferences/fdmsimple3dextoujumpsolver.hpp \
ql/experimental/finitedifferences/fdmspreadpayoffinnervalue.hpp \
ql/experimental/finitedifferences/fdmsquarerootfwdop.hpp \
ql/experimental/finitedifferences/fdmvppstartlimitstepcondition.hpp \
ql/experimental/finitedifferences/fdmvppstepcondition.hpp \
ql/experimental/finitedifferences/fdmvppstepconditionfactory.hpp \
ql/experimental/finitedifferences/fdsimpleextoujumpswingengine.hpp \
ql/experimental/finitedifferences/fdsimpleextoustorageengine.hpp \
ql/experimental/finitedifferences/fdsimpleklugeextouvppengine.hpp \
ql/experimental/finitedifferences/glued1dmesher.hpp \
ql/experimental/finitedifferences/modtriplebandlinearop.hpp \
ql/experimental/finitedifferences/vanillavppoption.hpp \
ql/experimental/fx/blackdeltacalculator.hpp \
ql/experimental/fx/deltavolquote.hpp \
ql/experimental/inflation/cpicapfloorengines.hpp \
ql/experimental/inflation/cpicapfloortermpricesurface.hpp \
ql/experimental/inflation/genericindexes.hpp \
ql/experimental/inflation/interpolatedyoyoptionletstripper.hpp \
ql/experimental/inflation/kinterpolatedyoyoptionletvolatilitysurface.hpp \
ql/experimental/inflation/piecewiseyoyoptionletvolatility.hpp \
ql/experimental/inflation/polynomial2Dspline.hpp \
ql/experimental/inflation/yoycapfloortermpricesurface.hpp \
ql/experimental/inflation/yoyinflationoptionletvolatilitystructure2.hpp \
ql/experimental/inflation/yoyoptionlethelpers.hpp \
ql/experimental/inflation/yoyoptionletstripper.hpp \
ql/experimental/lattices/extendedbinomialtree.hpp \
ql/experimental/math/adaptiverungekutta.hpp \
ql/experimental/math/claytoncopularng.hpp \
ql/experimental/math/complexarray.hpp \
ql/experimental/math/expm.hpp \
ql/experimental/math/farliegumbelmorgensterncopularng.hpp \
ql/experimental/math/frankcopularng.hpp \
ql/experimental/math/zigguratrng.hpp \
ql/experimental/mcbasket/adaptedpathpayoff.hpp \
ql/experimental/mcbasket/longstaffschwartzmultipathpricer.hpp \
ql/experimental/mcbasket/mcamericanpathengine.hpp \
ql/experimental/mcbasket/mclongstaffschwartzpathengine.hpp \
ql/experimental/mcbasket/mcpathbasketengine.hpp \
ql/experimental/mcbasket/pathmultiassetoption.hpp \
ql/experimental/mcbasket/pathpayoff.hpp \
ql/experimental/models/atmadjustedsmilesection.hpp \
ql/experimental/models/atmsmilesection.hpp \
ql/experimental/models/kahalesmilesection.hpp \
ql/experimental/models/markovfunctional.hpp \
ql/experimental/models/markovfunctionalcapfloorengine.hpp \
ql/experimental/models/markovfunctionalswaptionengine.hpp \
ql/experimental/models/mfstateprocess.hpp \
ql/experimental/models/smilesectionutils.hpp \
ql/experimental/processes/extendedblackscholesprocess.hpp \
ql/experimental/processes/extendedornsteinuhlenbeckprocess.hpp \
ql/experimental/processes/extouwithjumpsprocess.hpp \
ql/experimental/processes/gemanroncoroniprocess.hpp \
ql/experimental/processes/klugeextouprocess.hpp \
ql/experimental/processes/vegastressedblackscholesprocess.hpp \
ql/experimental/risk/sensitivityanalysis.hpp \
ql/experimental/shortrate/generalizedhullwhite.hpp \
ql/experimental/shortrate/generalizedornsteinuhlenbeckprocess.hpp \
ql/experimental/variancegamma/analyticvariancegammaengine.hpp \
ql/experimental/variancegamma/fftengine.hpp \
ql/experimental/variancegamma/fftvanillaengine.hpp \
ql/experimental/variancegamma/fftvariancegammaengine.hpp \
ql/experimental/variancegamma/variancegammamodel.hpp \
ql/experimental/variancegamma/variancegammaprocess.hpp \
ql/experimental/varianceoption/integralhestonvarianceoptionengine.hpp \
ql/experimental/varianceoption/varianceoption.hpp \
ql/experimental/volatility/abcdatmvolcurve.hpp \
ql/experimental/volatility/blackatmvolcurve.hpp \
ql/experimental/volatility/blackvolsurface.hpp \
ql/experimental/volatility/equityfxvolsurface.hpp \
ql/experimental/volatility/extendedblackvariancecurve.hpp \
ql/experimental/volatility/extendedblackvariancesurface.hpp \
ql/experimental/volatility/interestratevolsurface.hpp \
ql/experimental/volatility/sabrvolsurface.hpp \
ql/experimental/volatility/volcube.hpp \
ql/grid.hpp \
ql/handle.hpp \
ql/index.hpp \
ql/indexes/bmaindex.hpp \
ql/indexes/ibor/audlibor.hpp \
ql/indexes/ibor/cadlibor.hpp \
ql/indexes/ibor/cdor.hpp \
ql/indexes/ibor/chflibor.hpp \
ql/indexes/ibor/dkklibor.hpp \
ql/indexes/ibor/eonia.hpp \
ql/indexes/ibor/euribor.hpp \
ql/indexes/ibor/eurlibor.hpp \
ql/indexes/ibor/gbplibor.hpp \
ql/indexes/ibor/jibar.hpp \
ql/indexes/ibor/jpylibor.hpp \
ql/indexes/ibor/libor.hpp \
ql/indexes/ibor/nzdlibor.hpp \
ql/indexes/ibor/seklibor.hpp \
ql/indexes/ibor/sonia.hpp \
ql/indexes/ibor/tibor.hpp \
ql/indexes/ibor/trlibor.hpp \
ql/indexes/ibor/usdlibor.hpp \
ql/indexes/ibor/zibor.hpp \
ql/indexes/iborindex.hpp \
ql/indexes/indexmanager.hpp \
ql/indexes/inflation/aucpi.hpp \
ql/indexes/inflation/euhicp.hpp \
ql/indexes/inflation/frhicp.hpp \
ql/indexes/inflation/ukrpi.hpp \
ql/indexes/inflation/uscpi.hpp \
ql/indexes/inflationindex.hpp \
ql/indexes/interestrateindex.hpp \
ql/indexes/region.hpp \
ql/indexes/swap/chfliborswap.hpp \
ql/indexes/swap/euriborswap.hpp \
ql/indexes/swap/eurliborswap.hpp \
ql/indexes/swap/gbpliborswap.hpp \
ql/indexes/swap/jpyliborswap.hpp \
ql/indexes/swap/usdliborswap.hpp \
ql/indexes/swapindex.hpp \
ql/instrument.hpp \
ql/instruments/asianoption.hpp \
ql/instruments/assetswap.hpp \
ql/instruments/averagetype.hpp \
ql/instruments/barrieroption.hpp \
ql/instruments/barriertype.hpp \
ql/instruments/basketoption.hpp \
ql/instruments/bmaswap.hpp \
ql/instruments/bond.hpp \
ql/instruments/bonds/btp.hpp \
ql/instruments/bonds/cmsratebond.hpp \
ql/instruments/bonds/cpibond.hpp \
ql/instruments/bonds/fixedratebond.hpp \
ql/instruments/bonds/floatingratebond.hpp \
ql/instruments/bonds/zerocouponbond.hpp \
ql/instruments/callabilityschedule.hpp \
ql/instruments/capfloor.hpp \
ql/instruments/claim.hpp \
ql/instruments/cliquetoption.hpp \
ql/instruments/compositeinstrument.hpp \
ql/instruments/cpicapfloor.hpp \
ql/instruments/cpiswap.hpp \
ql/instruments/creditdefaultswap.hpp \
ql/instruments/dividendbarrieroption.hpp \
ql/instruments/dividendschedule.hpp \
ql/instruments/dividendvanillaoption.hpp \
ql/instruments/europeanoption.hpp \
ql/instruments/fixedratebondforward.hpp \
ql/instruments/forward.hpp \
ql/instruments/forwardrateagreement.hpp \
ql/instruments/forwardvanillaoption.hpp \
ql/instruments/impliedvolatility.hpp \
ql/instruments/inflationcapfloor.hpp \
ql/instruments/lookbackoption.hpp \
ql/instruments/makecapfloor.hpp \
ql/instruments/makecms.hpp \
ql/instruments/makeois.hpp \
ql/instruments/makeswaption.hpp \
ql/instruments/makevanillaswap.hpp \
ql/instruments/makeyoyinflationcapfloor.hpp \
ql/instruments/multiassetoption.hpp \
ql/instruments/oneassetoption.hpp \
ql/instruments/overnightindexedswap.hpp \
ql/instruments/payoffs.hpp \
ql/instruments/quantobarrieroption.hpp \
ql/instruments/quantoforwardvanillaoption.hpp \
ql/instruments/quantovanillaoption.hpp \
ql/instruments/stickyratchet.hpp \
ql/instruments/stock.hpp \
ql/instruments/swap.hpp \
ql/instruments/swaption.hpp \
ql/instruments/vanillaoption.hpp \
ql/instruments/vanillastorageoption.hpp \
ql/instruments/vanillaswap.hpp \
ql/instruments/vanillaswingoption.hpp \
ql/instruments/varianceswap.hpp \
ql/instruments/yearonyearinflationswap.hpp \
ql/instruments/zerocouponinflationswap.hpp \
ql/interestrate.hpp \
ql/legacy/libormarketmodels/lfmcovarparam.hpp \
ql/legacy/libormarketmodels/lfmcovarproxy.hpp \
ql/legacy/libormarketmodels/lfmhullwhiteparam.hpp \
ql/legacy/libormarketmodels/lfmprocess.hpp \
ql/legacy/libormarketmodels/lfmswaptionengine.hpp \
ql/legacy/libormarketmodels/liborforwardmodel.hpp \
ql/legacy/libormarketmodels/lmconstwrappercorrmodel.hpp \
ql/legacy/libormarketmodels/lmconstwrappervolmodel.hpp \
ql/legacy/libormarketmodels/lmcorrmodel.hpp \
ql/legacy/libormarketmodels/lmexpcorrmodel.hpp \
ql/legacy/libormarketmodels/lmextlinexpvolmodel.hpp \
ql/legacy/libormarketmodels/lmfixedvolmodel.hpp \
ql/legacy/libormarketmodels/lmlinexpcorrmodel.hpp \
ql/legacy/libormarketmodels/lmlinexpvolmodel.hpp \
ql/legacy/libormarketmodels/lmvolmodel.hpp \
ql/math/array.hpp \
ql/math/autocovariance.hpp \
ql/math/bernsteinpolynomial.hpp \
ql/math/beta.hpp \
ql/math/bspline.hpp \
ql/math/comparison.hpp \
ql/math/copulas/alimikhailhaqcopula.hpp \
ql/math/copulas/claytoncopula.hpp \
ql/math/copulas/farliegumbelmorgensterncopula.hpp \
ql/math/copulas/frankcopula.hpp \
ql/math/copulas/galamboscopula.hpp \
ql/math/copulas/gaussiancopula.hpp \
ql/math/copulas/gumbelcopula.hpp \
ql/math/copulas/huslerreisscopula.hpp \
ql/math/copulas/independentcopula.hpp \
ql/math/copulas/marshallolkincopula.hpp \
ql/math/copulas/maxcopula.hpp \
ql/math/copulas/mincopula.hpp \
ql/math/copulas/plackettcopula.hpp \
ql/math/curve.hpp \
ql/math/distributions/binomialdistribution.hpp \
ql/math/distributions/bivariatenormaldistribution.hpp \
ql/math/distributions/chisquaredistribution.hpp \
ql/math/distributions/gammadistribution.hpp \
ql/math/distributions/normaldistribution.hpp \
ql/math/distributions/poissondistribution.hpp \
ql/math/distributions/studenttdistribution.hpp \
ql/math/domain.hpp \
ql/math/errorfunction.hpp \
ql/math/factorial.hpp \
ql/math/fastfouriertransform.hpp \
ql/math/functional.hpp \
ql/math/generallinearleastsquares.hpp \
ql/math/incompletegamma.hpp \
ql/math/integrals/gaussianorthogonalpolynomial.hpp \
ql/math/integrals/gaussianquadratures.hpp \
ql/math/integrals/gausslobattointegral.hpp \
ql/math/integrals/integral.hpp \
ql/math/integrals/kronrodintegral.hpp \
ql/math/integrals/segmentintegral.hpp \
ql/math/integrals/simpsonintegral.hpp \
ql/math/integrals/trapezoidintegral.hpp \
ql/math/interpolation.hpp \
ql/math/interpolations/abcdinterpolation.hpp \
ql/math/interpolations/backwardflatinterpolation.hpp \
ql/math/interpolations/bicubicsplineinterpolation.hpp \
ql/math/interpolations/bilinearinterpolation.hpp \
ql/math/interpolations/convexmonotoneinterpolation.hpp \
ql/math/interpolations/cubicinterpolation.hpp \
ql/math/interpolations/extrapolation.hpp \
ql/math/interpolations/flatextrapolation2d.hpp \
ql/math/interpolations/forwardflatinterpolation.hpp \
ql/math/interpolations/interpolation2d.hpp \
ql/math/interpolations/kernelinterpolation.hpp \
ql/math/interpolations/kernelinterpolation2d.hpp \
ql/math/interpolations/linearinterpolation.hpp \
ql/math/interpolations/loginterpolation.hpp \
ql/math/interpolations/mixedinterpolation.hpp \
ql/math/interpolations/multicubicspline.hpp \
ql/math/interpolations/sabrinterpolation.hpp \
ql/math/kernelfunctions.hpp \
ql/math/lexicographicalview.hpp \
ql/math/linearleastsquaresregression.hpp \
ql/math/matrix.hpp \
ql/math/matrixutilities/basisincompleteordered.hpp \
ql/math/matrixutilities/bicgstab.hpp \
ql/math/matrixutilities/choleskydecomposition.hpp \
ql/math/matrixutilities/factorreduction.hpp \
ql/math/matrixutilities/getcovariance.hpp \
ql/math/matrixutilities/pseudosqrt.hpp \
ql/math/matrixutilities/qrdecomposition.hpp \
ql/math/matrixutilities/sparseilupreconditioner.hpp \
ql/math/matrixutilities/sparsematrix.hpp \
ql/math/matrixutilities/svd.hpp \
ql/math/matrixutilities/symmetricschurdecomposition.hpp \
ql/math/matrixutilities/tapcorrelations.hpp \
ql/math/matrixutilities/tqreigendecomposition.hpp \
ql/math/optimization/armijo.hpp \
ql/math/optimization/bfgs.hpp \
ql/math/optimization/conjugategradient.hpp \
ql/math/optimization/constraint.hpp \
ql/math/optimization/costfunction.hpp \
ql/math/optimization/differentialevolution.hpp \
ql/math/optimization/endcriteria.hpp \
ql/math/optimization/leastsquare.hpp \
ql/math/optimization/levenbergmarquardt.hpp \
ql/math/optimization/linesearch.hpp \
ql/math/optimization/linesearchbasedmethod.hpp \
ql/math/optimization/lmdif.hpp \
ql/math/optimization/method.hpp \
ql/math/optimization/problem.hpp \
ql/math/optimization/projectedcostfunction.hpp \
ql/math/optimization/simplex.hpp \
ql/math/optimization/spherecylinder.hpp \
ql/math/optimization/steepestdescent.hpp \
ql/math/primenumbers.hpp \
ql/math/quadratic.hpp \
ql/math/randomnumbers/boxmullergaussianrng.hpp \
ql/math/randomnumbers/centrallimitgaussianrng.hpp \
ql/math/randomnumbers/faurersg.hpp \
ql/math/randomnumbers/haltonrsg.hpp \
ql/math/randomnumbers/inversecumulativerng.hpp \
ql/math/randomnumbers/inversecumulativersg.hpp \
ql/math/randomnumbers/knuthuniformrng.hpp \
ql/math/randomnumbers/latticersg.hpp \
ql/math/randomnumbers/latticerules.hpp \
ql/math/randomnumbers/lecuyeruniformrng.hpp \
ql/math/randomnumbers/mt19937uniformrng.hpp \
ql/math/randomnumbers/randomizedlds.hpp \
ql/math/randomnumbers/randomsequencegenerator.hpp \
ql/math/randomnumbers/ranluxuniformrng.hpp \
ql/math/randomnumbers/rngtraits.hpp \
ql/math/randomnumbers/seedgenerator.hpp \
ql/math/randomnumbers/sobolbrownianbridgersg.hpp \
ql/math/randomnumbers/sobolrsg.hpp \
ql/math/richardsonextrapolation.hpp \
ql/math/rounding.hpp \
ql/math/sampledcurve.hpp \
ql/math/solver1d.hpp \
ql/math/solvers1d/bisection.hpp \
ql/math/solvers1d/brent.hpp \
ql/math/solvers1d/falseposition.hpp \
ql/math/solvers1d/finitedifferencenewtonsafe.hpp \
ql/math/solvers1d/newton.hpp \
ql/math/solvers1d/newtonsafe.hpp \
ql/math/solvers1d/ridder.hpp \
ql/math/solvers1d/secant.hpp \
ql/math/statistics/convergencestatistics.hpp \
ql/math/statistics/discrepancystatistics.hpp \
ql/math/statistics/gaussianstatistics.hpp \
ql/math/statistics/generalstatistics.hpp \
ql/math/statistics/histogram.hpp \
ql/math/statistics/incrementalstatistics.hpp \
ql/math/statistics/riskstatistics.hpp \
ql/math/statistics/sequencestatistics.hpp \
ql/math/statistics/statistics.hpp \
ql/math/surface.hpp \
ql/math/transformedgrid.hpp \
ql/mathconstants.hpp \
ql/methods/finitedifferences/americancondition.hpp \
ql/methods/finitedifferences/boundarycondition.hpp \
ql/methods/finitedifferences/bsmoperator.hpp \
ql/methods/finitedifferences/bsmtermoperator.hpp \
ql/methods/finitedifferences/cranknicolson.hpp \
ql/methods/finitedifferences/dminus.hpp \
ql/methods/finitedifferences/dplus.hpp \
ql/methods/finitedifferences/dplusdminus.hpp \
ql/methods/finitedifferences/dzero.hpp \
ql/methods/finitedifferences/expliciteuler.hpp \
ql/methods/finitedifferences/fdtypedefs.hpp \
ql/methods/finitedifferences/finitedifferencemodel.hpp \
ql/methods/finitedifferences/impliciteuler.hpp \
ql/methods/finitedifferences/meshers/concentrating1dmesher.hpp \
ql/methods/finitedifferences/meshers/exponentialjump1dmesher.hpp \
ql/methods/finitedifferences/meshers/fdm1dmesher.hpp \
ql/methods/finitedifferences/meshers/fdmblackscholesmesher.hpp \
ql/methods/finitedifferences/meshers/fdmblackscholesmultistrikemesher.hpp \
ql/methods/finitedifferences/meshers/fdmhestonvariancemesher.hpp \
ql/methods/finitedifferences/meshers/fdmmesher.hpp \
ql/methods/finitedifferences/meshers/fdmmeshercomposite.hpp \
ql/methods/finitedifferences/meshers/fdmsimpleprocess1dmesher.hpp \
ql/methods/finitedifferences/meshers/predefined1dmesher.hpp \
ql/methods/finitedifferences/meshers/uniform1dmesher.hpp \
ql/methods/finitedifferences/meshers/uniformgridmesher.hpp \
ql/methods/finitedifferences/mixedscheme.hpp \
ql/methods/finitedifferences/onefactoroperator.hpp \
ql/methods/finitedifferences/operatorfactory.hpp \
ql/methods/finitedifferences/operators/fdm2dblackscholesop.hpp \
ql/methods/finitedifferences/operators/fdmbatesop.hpp \
ql/methods/finitedifferences/operators/fdmblackscholesop.hpp \
ql/methods/finitedifferences/operators/fdmg2op.hpp \
ql/methods/finitedifferences/operators/fdmhestonhullwhiteop.hpp \
ql/methods/finitedifferences/operators/fdmhestonop.hpp \
ql/methods/finitedifferences/operators/fdmhullwhiteop.hpp \
ql/methods/finitedifferences/operators/fdmlinearop.hpp \
ql/methods/finitedifferences/operators/fdmlinearopcomposite.hpp \
ql/methods/finitedifferences/operators/fdmlinearopiterator.hpp \
ql/methods/finitedifferences/operators/fdmlinearoplayout.hpp \
ql/methods/finitedifferences/operators/firstderivativeop.hpp \
ql/methods/finitedifferences/operators/ninepointlinearop.hpp \
ql/methods/finitedifferences/operators/secondderivativeop.hpp \
ql/methods/finitedifferences/operators/secondordermixedderivativeop.hpp \
ql/methods/finitedifferences/operators/triplebandlinearop.hpp \
ql/methods/finitedifferences/operatortraits.hpp \
ql/methods/finitedifferences/parallelevolver.hpp \
ql/methods/finitedifferences/pde.hpp \
ql/methods/finitedifferences/pdebsm.hpp \
ql/methods/finitedifferences/pdeshortrate.hpp \
ql/methods/finitedifferences/schemes/boundaryconditionschemehelper.hpp \
ql/methods/finitedifferences/schemes/craigsneydscheme.hpp \
ql/methods/finitedifferences/schemes/douglasscheme.hpp \
ql/methods/finitedifferences/schemes/expliciteulerscheme.hpp \
ql/methods/finitedifferences/schemes/hundsdorferscheme.hpp \
ql/methods/finitedifferences/schemes/impliciteulerscheme.hpp \
ql/methods/finitedifferences/schemes/modifiedcraigsneydscheme.hpp \
ql/methods/finitedifferences/shoutcondition.hpp \
ql/methods/finitedifferences/solvers/fdm1dimsolver.hpp \
ql/methods/finitedifferences/solvers/fdm2dblackscholessolver.hpp \
ql/methods/finitedifferences/solvers/fdm2dimsolver.hpp \
ql/methods/finitedifferences/solvers/fdm3dimsolver.hpp \
ql/methods/finitedifferences/solvers/fdmbackwardsolver.hpp \
ql/methods/finitedifferences/solvers/fdmbatessolver.hpp \
ql/methods/finitedifferences/solvers/fdmblackscholessolver.hpp \
ql/methods/finitedifferences/solvers/fdmg2solver.hpp \
ql/methods/finitedifferences/solvers/fdmhestonhullwhitesolver.hpp \
ql/methods/finitedifferences/solvers/fdmhestonsolver.hpp \
ql/methods/finitedifferences/solvers/fdmhullwhitesolver.hpp \
ql/methods/finitedifferences/solvers/fdmndimsolver.hpp \
ql/methods/finitedifferences/solvers/fdmsimple2dbssolver.hpp \
ql/methods/finitedifferences/solvers/fdmsolverdesc.hpp \
ql/methods/finitedifferences/stepcondition.hpp \
ql/methods/finitedifferences/stepconditions/fdmamericanstepcondition.hpp \
ql/methods/finitedifferences/stepconditions/fdmarithmeticaveragecondition.hpp \
ql/methods/finitedifferences/stepconditions/fdmbermudanstepcondition.hpp \
ql/methods/finitedifferences/stepconditions/fdmsimplestoragecondition.hpp \
ql/methods/finitedifferences/stepconditions/fdmsimpleswingcondition.hpp \
ql/methods/finitedifferences/stepconditions/fdmsnapshotcondition.hpp \
ql/methods/finitedifferences/stepconditions/fdmstepconditioncomposite.hpp \
ql/methods/finitedifferences/trbdf2.hpp \
ql/methods/finitedifferences/tridiagonaloperator.hpp \
ql/methods/finitedifferences/utilities/fdmaffinemodelswapinnervalue.hpp \
ql/methods/finitedifferences/utilities/fdmaffinemodeltermstructure.hpp \
ql/methods/finitedifferences/utilities/fdmboundaryconditionset.hpp \
ql/methods/finitedifferences/utilities/fdmdirichletboundary.hpp \
ql/methods/finitedifferences/utilities/fdmdividendhandler.hpp \
ql/methods/finitedifferences/utilities/fdmindicesonboundary.hpp \
ql/methods/finitedifferences/utilities/fdminnervaluecalculator.hpp \
ql/methods/finitedifferences/utilities/fdmquantohelper.hpp \
ql/methods/finitedifferences/utilities/fdmtimedepdirichletboundary.hpp \
ql/methods/finitedifferences/zerocondition.hpp \
ql/methods/lattices/binomialtree.hpp \
ql/methods/lattices/bsmlattice.hpp \
ql/methods/lattices/lattice.hpp \
ql/methods/lattices/lattice1d.hpp \
ql/methods/lattices/lattice2d.hpp \
ql/methods/lattices/tree.hpp \
ql/methods/lattices/trinomialtree.hpp \
ql/methods/montecarlo/brownianbridge.hpp \
ql/methods/montecarlo/earlyexercisepathpricer.hpp \
ql/methods/montecarlo/exercisestrategy.hpp \
ql/methods/montecarlo/genericlsregression.hpp \
ql/methods/montecarlo/longstaffschwartzpathpricer.hpp \
ql/methods/montecarlo/lsmbasissystem.hpp \
ql/methods/montecarlo/mctraits.hpp \
ql/methods/montecarlo/montecarlomodel.hpp \
ql/methods/montecarlo/multipath.hpp \
ql/methods/montecarlo/multipathgenerator.hpp \
ql/methods/montecarlo/nodedata.hpp \
ql/methods/montecarlo/parametricexercise.hpp \
ql/methods/montecarlo/path.hpp \
ql/methods/montecarlo/pathgenerator.hpp \
ql/methods/montecarlo/pathpricer.hpp \
ql/methods/montecarlo/sample.hpp \
ql/models/calibrationhelper.hpp \
ql/models/equity/batesmodel.hpp \
ql/models/equity/gjrgarchmodel.hpp \
ql/models/equity/hestonmodel.hpp \
ql/models/equity/hestonmodelhelper.hpp \
ql/models/equity/piecewisetimedependenthestonmodel.hpp \
ql/models/marketmodels/accountingengine.hpp \
ql/models/marketmodels/browniangenerator.hpp \
ql/models/marketmodels/browniangenerators/mtbrowniangenerator.hpp \
ql/models/marketmodels/browniangenerators/sobolbrowniangenerator.hpp \
ql/models/marketmodels/callability/bermudanswaptionexercisevalue.hpp \
ql/models/marketmodels/callability/collectnodedata.hpp \
ql/models/marketmodels/callability/exercisevalue.hpp \
ql/models/marketmodels/callability/lsstrategy.hpp \
ql/models/marketmodels/callability/marketmodelbasissystem.hpp \
ql/models/marketmodels/callability/marketmodelparametricexercise.hpp \
ql/models/marketmodels/callability/nodedataprovider.hpp \
ql/models/marketmodels/callability/nothingexercisevalue.hpp \
ql/models/marketmodels/callability/parametricexerciseadapter.hpp \
ql/models/marketmodels/callability/swapbasissystem.hpp \
ql/models/marketmodels/callability/swapforwardbasissystem.hpp \
ql/models/marketmodels/callability/swapratetrigger.hpp \
ql/models/marketmodels/callability/triggeredswapexercise.hpp \
ql/models/marketmodels/callability/upperboundengine.hpp \
ql/models/marketmodels/constrainedevolver.hpp \
ql/models/marketmodels/correlations/cotswapfromfwdcorrelation.hpp \
ql/models/marketmodels/correlations/expcorrelations.hpp \
ql/models/marketmodels/correlations/timehomogeneousforwardcorrelation.hpp \
ql/models/marketmodels/curvestate.hpp \
ql/models/marketmodels/curvestates/cmswapcurvestate.hpp \
ql/models/marketmodels/curvestates/coterminalswapcurvestate.hpp \
ql/models/marketmodels/curvestates/lmmcurvestate.hpp \
ql/models/marketmodels/discounter.hpp \
ql/models/marketmodels/driftcomputation/cmsmmdriftcalculator.hpp \
ql/models/marketmodels/driftcomputation/lmmdriftcalculator.hpp \
ql/models/marketmodels/driftcomputation/lmmnormaldriftcalculator.hpp \
ql/models/marketmodels/driftcomputation/smmdriftcalculator.hpp \
ql/models/marketmodels/duffsdeviceinnerproduct.hpp \
ql/models/marketmodels/evolutiondescription.hpp \
ql/models/marketmodels/evolver.hpp \
ql/models/marketmodels/evolvers/lognormalcmswapratepc.hpp \
ql/models/marketmodels/evolvers/lognormalcotswapratepc.hpp \
ql/models/marketmodels/evolvers/lognormalfwdrateballand.hpp \
ql/models/marketmodels/evolvers/lognormalfwdrateeuler.hpp \
ql/models/marketmodels/evolvers/lognormalfwdrateeulerconstrained.hpp \
ql/models/marketmodels/evolvers/lognormalfwdrateiballand.hpp \
ql/models/marketmodels/evolvers/lognormalfwdrateipc.hpp \
ql/models/marketmodels/evolvers/lognormalfwdratepc.hpp \
ql/models/marketmodels/evolvers/marketmodelvolprocess.hpp \
ql/models/marketmodels/evolvers/normalfwdratepc.hpp \
ql/models/marketmodels/evolvers/svddfwdratepc.hpp \
ql/models/marketmodels/evolvers/volprocesses/squarerootandersen.hpp \
ql/models/marketmodels/forwardforwardmappings.hpp \
ql/models/marketmodels/historicalforwardratesanalysis.hpp \
ql/models/marketmodels/historicalratesanalysis.hpp \
ql/models/marketmodels/marketmodel.hpp \
ql/models/marketmodels/marketmodeldifferences.hpp \
ql/models/marketmodels/models/abcdvol.hpp \
ql/models/marketmodels/models/alphafinder.hpp \
ql/models/marketmodels/models/alphaform.hpp \
ql/models/marketmodels/models/alphaformconcrete.hpp \
ql/models/marketmodels/models/capletcoterminalalphacalibration.hpp \
ql/models/marketmodels/models/capletcoterminalmaxhomogeneity.hpp \
ql/models/marketmodels/models/capletcoterminalperiodic.hpp \
ql/models/marketmodels/models/capletcoterminalswaptioncalibration.hpp \
ql/models/marketmodels/models/cotswaptofwdadapter.hpp \
ql/models/marketmodels/models/ctsmmcapletcalibration.hpp \
ql/models/marketmodels/models/flatvol.hpp \
ql/models/marketmodels/models/fwdperiodadapter.hpp \
ql/models/marketmodels/models/fwdtocotswapadapter.hpp \
ql/models/marketmodels/models/piecewiseconstantabcdvariance.hpp \
ql/models/marketmodels/models/piecewiseconstantvariance.hpp \
ql/models/marketmodels/models/pseudorootfacade.hpp \
ql/models/marketmodels/models/volatilityinterpolationspecifier.hpp \
ql/models/marketmodels/models/volatilityinterpolationspecifierabcd.hpp \
ql/models/marketmodels/multiproduct.hpp \
ql/models/marketmodels/pathwiseaccountingengine.hpp \
ql/models/marketmodels/pathwisediscounter.hpp \
ql/models/marketmodels/pathwisegreeks/bumpinstrumentjacobian.hpp \
ql/models/marketmodels/pathwisegreeks/ratepseudorootjacobian.hpp \
ql/models/marketmodels/pathwisegreeks/swaptionpseudojacobian.hpp \
ql/models/marketmodels/pathwisegreeks/vegabumpcluster.hpp \
ql/models/marketmodels/pathwisemultiproduct.hpp \
ql/models/marketmodels/piecewiseconstantcorrelation.hpp \
ql/models/marketmodels/products/compositeproduct.hpp \
ql/models/marketmodels/products/multiproductcomposite.hpp \
ql/models/marketmodels/products/multiproductmultistep.hpp \
ql/models/marketmodels/products/multiproductonestep.hpp \
ql/models/marketmodels/products/multistep/callspecifiedmultiproduct.hpp \
ql/models/marketmodels/products/multistep/cashrebate.hpp \
ql/models/marketmodels/products/multistep/exerciseadapter.hpp \
ql/models/marketmodels/products/multistep/multistepcoinitialswaps.hpp \
ql/models/marketmodels/products/multistep/multistepcoterminalswaps.hpp \
ql/models/marketmodels/products/multistep/multistepcoterminalswaptions.hpp \
ql/models/marketmodels/products/multistep/multistepforwards.hpp \
ql/models/marketmodels/products/multistep/multistepinversefloater.hpp \
ql/models/marketmodels/products/multistep/multistepnothing.hpp \
ql/models/marketmodels/products/multistep/multistepoptionlets.hpp \
ql/models/marketmodels/products/multistep/multisteppathwisewrapper.hpp \
ql/models/marketmodels/products/multistep/multistepperiodcapletswaptions.hpp \
ql/models/marketmodels/products/multistep/multistepratchet.hpp \
ql/models/marketmodels/products/multistep/multistepswap.hpp \
ql/models/marketmodels/products/multistep/multistepswaption.hpp \
ql/models/marketmodels/products/multistep/multisteptarn.hpp \
ql/models/marketmodels/products/onestep/onestepcoinitialswaps.hpp \
ql/models/marketmodels/products/onestep/onestepcoterminalswaps.hpp \
ql/models/marketmodels/products/onestep/onestepforwards.hpp \
ql/models/marketmodels/products/onestep/onestepoptionlets.hpp \
ql/models/marketmodels/products/pathwise/pathwiseproductcallspecified.hpp \
ql/models/marketmodels/products/pathwise/pathwiseproductcaplet.hpp \
ql/models/marketmodels/products/pathwise/pathwiseproductcashrebate.hpp \
ql/models/marketmodels/products/pathwise/pathwiseproductinversefloater.hpp \
ql/models/marketmodels/products/pathwise/pathwiseproductswap.hpp \
ql/models/marketmodels/products/pathwise/pathwiseproductswaption.hpp \
ql/models/marketmodels/products/singleproductcomposite.hpp \
ql/models/marketmodels/proxygreekengine.hpp \
ql/models/marketmodels/swapforwardmappings.hpp \
ql/models/marketmodels/utilities.hpp \
ql/models/model.hpp \
ql/models/parameter.hpp \
ql/models/shortrate/calibrationhelpers/caphelper.hpp \
ql/models/shortrate/calibrationhelpers/swaptionhelper.hpp \
ql/models/shortrate/onefactormodel.hpp \
ql/models/shortrate/onefactormodels/blackkarasinski.hpp \
ql/models/shortrate/onefactormodels/coxingersollross.hpp \
ql/models/shortrate/onefactormodels/extendedcoxingersollross.hpp \
ql/models/shortrate/onefactormodels/hullwhite.hpp \
ql/models/shortrate/onefactormodels/vasicek.hpp \
ql/models/shortrate/twofactormodel.hpp \
ql/models/shortrate/twofactormodels/g2.hpp \
ql/models/volatility/constantestimator.hpp \
ql/models/volatility/garch.hpp \
ql/models/volatility/garmanklass.hpp \
ql/models/volatility/simplelocalestimator.hpp \
ql/money.hpp \
ql/numericalmethod.hpp \
ql/option.hpp \
ql/patterns/composite.hpp \
ql/patterns/curiouslyrecurring.hpp \
ql/patterns/lazyobject.hpp \
ql/patterns/observable.hpp \
ql/patterns/singleton.hpp \
ql/patterns/visitor.hpp \
ql/payoff.hpp \
ql/position.hpp \
ql/prices.hpp \
ql/pricingengine.hpp \
ql/pricingengines/americanpayoffatexpiry.hpp \
ql/pricingengines/americanpayoffathit.hpp \
ql/pricingengines/asian/analytic_cont_geom_av_price.hpp \
ql/pricingengines/asian/analytic_discr_geom_av_price.hpp \
ql/pricingengines/asian/analytic_discr_geom_av_strike.hpp \
ql/pricingengines/asian/fdblackscholesasianengine.hpp \
ql/pricingengines/asian/mc_discr_arith_av_price.hpp \
ql/pricingengines/asian/mc_discr_arith_av_strike.hpp \
ql/pricingengines/asian/mc_discr_geom_av_price.hpp \
ql/pricingengines/asian/mcdiscreteasianengine.hpp \
ql/pricingengines/barrier/analyticbarrierengine.hpp \
ql/pricingengines/barrier/fdblackscholesbarrierengine.hpp \
ql/pricingengines/barrier/fdblackscholesrebateengine.hpp \
ql/pricingengines/barrier/fdhestonbarrierengine.hpp \
ql/pricingengines/barrier/fdhestonrebateengine.hpp \
ql/pricingengines/barrier/mcbarrierengine.hpp \
ql/pricingengines/basket/fd2dblackscholesvanillaengine.hpp \
ql/pricingengines/basket/kirkengine.hpp \
ql/pricingengines/basket/mcamericanbasketengine.hpp \
ql/pricingengines/basket/mceuropeanbasketengine.hpp \
ql/pricingengines/basket/stulzengine.hpp \
ql/pricingengines/blackcalculator.hpp \
ql/pricingengines/blackformula.hpp \
ql/pricingengines/blackscholescalculator.hpp \
ql/pricingengines/bond/bondfunctions.hpp \
ql/pricingengines/bond/discountingbondengine.hpp \
ql/pricingengines/capfloor/analyticcapfloorengine.hpp \
ql/pricingengines/capfloor/blackcapfloorengine.hpp \
ql/pricingengines/capfloor/discretizedcapfloor.hpp \
ql/pricingengines/capfloor/mchullwhiteengine.hpp \
ql/pricingengines/capfloor/treecapfloorengine.hpp \
ql/pricingengines/cliquet/analyticcliquetengine.hpp \
ql/pricingengines/cliquet/analyticperformanceengine.hpp \
ql/pricingengines/cliquet/mcperformanceengine.hpp \
ql/pricingengines/credit/integralcdsengine.hpp \
ql/pricingengines/credit/midpointcdsengine.hpp \
ql/pricingengines/forward/forwardengine.hpp \
ql/pricingengines/forward/forwardperformanceengine.hpp \
ql/pricingengines/forward/mcvarianceswapengine.hpp \
ql/pricingengines/forward/replicatingvarianceswapengine.hpp \
ql/pricingengines/genericmodelengine.hpp \
ql/pricingengines/greeks.hpp \
ql/pricingengines/inflation/inflationcapfloorengines.hpp \
ql/pricingengines/latticeshortratemodelengine.hpp \
ql/pricingengines/lookback/analyticcontinuousfixedlookback.hpp \
ql/pricingengines/lookback/analyticcontinuousfloatinglookback.hpp \
ql/pricingengines/mclongstaffschwartzengine.hpp \
ql/pricingengines/mcsimulation.hpp \
ql/pricingengines/quanto/quantoengine.hpp \
ql/pricingengines/swap/discountingswapengine.hpp \
ql/pricingengines/swap/discretizedswap.hpp \
ql/pricingengines/swap/treeswapengine.hpp \
ql/pricingengines/swaption/blackswaptionengine.hpp \
ql/pricingengines/swaption/discretizedswaption.hpp \
ql/pricingengines/swaption/fdg2swaptionengine.hpp \
ql/pricingengines/swaption/fdhullwhiteswaptionengine.hpp \
ql/pricingengines/swaption/g2swaptionengine.hpp \
ql/pricingengines/swaption/jamshidianswaptionengine.hpp \
ql/pricingengines/swaption/treeswaptionengine.hpp \
ql/pricingengines/vanilla/analyticbsmhullwhiteengine.hpp \
ql/pricingengines/vanilla/analyticdigitalamericanengine.hpp \
ql/pricingengines/vanilla/analyticdividendeuropeanengine.hpp \
ql/pricingengines/vanilla/analyticeuropeanengine.hpp \
ql/pricingengines/vanilla/analyticgjrgarchengine.hpp \
ql/pricingengines/vanilla/analytich1hwengine.hpp \
ql/pricingengines/vanilla/analytichestonengine.hpp \
ql/pricingengines/vanilla/analytichestonhullwhiteengine.hpp \
ql/pricingengines/vanilla/analyticptdhestonengine.hpp \
ql/pricingengines/vanilla/baroneadesiwhaleyengine.hpp \
ql/pricingengines/vanilla/batesengine.hpp \
ql/pricingengines/vanilla/binomialengine.hpp \
ql/pricingengines/vanilla/bjerksundstenslandengine.hpp \
ql/pricingengines/vanilla/discretizedvanillaoption.hpp \
ql/pricingengines/vanilla/fdamericanengine.hpp \
ql/pricingengines/vanilla/fdbatesvanillaengine.hpp \
ql/pricingengines/vanilla/fdbermudanengine.hpp \
ql/pricingengines/vanilla/fdblackscholesvanillaengine.hpp \
ql/pricingengines/vanilla/fdconditions.hpp \
ql/pricingengines/vanilla/fddividendamericanengine.hpp \
ql/pricingengines/vanilla/fddividendengine.hpp \
ql/pricingengines/vanilla/fddividendeuropeanengine.hpp \
ql/pricingengines/vanilla/fddividendshoutengine.hpp \
ql/pricingengines/vanilla/fdeuropeanengine.hpp \
ql/pricingengines/vanilla/fdhestonhullwhitevanillaengine.hpp \
ql/pricingengines/vanilla/fdhestonvanillaengine.hpp \
ql/pricingengines/vanilla/fdmultiperiodengine.hpp \
ql/pricingengines/vanilla/fdshoutengine.hpp \
ql/pricingengines/vanilla/fdsimplebsswingengine.hpp \
ql/pricingengines/vanilla/fdstepconditionengine.hpp \
ql/pricingengines/vanilla/fdvanillaengine.hpp \
ql/pricingengines/vanilla/integralengine.hpp \
ql/pricingengines/vanilla/jumpdiffusionengine.hpp \
ql/pricingengines/vanilla/juquadraticengine.hpp \
ql/pricingengines/vanilla/mcamericanengine.hpp \
ql/pricingengines/vanilla/mcdigitalengine.hpp \
ql/pricingengines/vanilla/mceuropeanengine.hpp \
ql/pricingengines/vanilla/mceuropeangjrgarchengine.hpp \
ql/pricingengines/vanilla/mceuropeanhestonengine.hpp \
ql/pricingengines/vanilla/mchestonhullwhiteengine.hpp \
ql/pricingengines/vanilla/mcvanillaengine.hpp \
ql/processes/batesprocess.hpp \
ql/processes/blackscholesprocess.hpp \
ql/processes/endeulerdiscretization.hpp \
ql/processes/eulerdiscretization.hpp \
ql/processes/forwardmeasureprocess.hpp \
ql/processes/g2process.hpp \
ql/processes/geometricbrownianprocess.hpp \
ql/processes/gjrgarchprocess.hpp \
ql/processes/hestonprocess.hpp \
ql/processes/hullwhiteprocess.hpp \
ql/processes/hybridhestonhullwhiteprocess.hpp \
ql/processes/jointstochasticprocess.hpp \
ql/processes/merton76process.hpp \
ql/processes/ornsteinuhlenbeckprocess.hpp \
ql/processes/squarerootprocess.hpp \
ql/processes/stochasticprocessarray.hpp \
ql/qldefines.hpp \
ql/quantlib.hpp \
ql/quote.hpp \
ql/quotes/compositequote.hpp \
ql/quotes/derivedquote.hpp \
ql/quotes/eurodollarfuturesquote.hpp \
ql/quotes/forwardswapquote.hpp \
ql/quotes/forwardvaluequote.hpp \
ql/quotes/futuresconvadjustmentquote.hpp \
ql/quotes/impliedstddevquote.hpp \
ql/quotes/lastfixingquote.hpp \
ql/quotes/simplequote.hpp \
ql/settings.hpp \
ql/stochasticprocess.hpp \
ql/termstructure.hpp \
ql/termstructures/bootstraperror.hpp \
ql/termstructures/bootstraphelper.hpp \
ql/termstructures/credit/defaultdensitystructure.hpp \
ql/termstructures/credit/defaultprobabilityhelpers.hpp \
ql/termstructures/credit/flathazardrate.hpp \
ql/termstructures/credit/hazardratestructure.hpp \
ql/termstructures/credit/interpolateddefaultdensitycurve.hpp \
ql/termstructures/credit/interpolatedhazardratecurve.hpp \
ql/termstructures/credit/interpolatedsurvivalprobabilitycurve.hpp \
ql/termstructures/credit/piecewisedefaultcurve.hpp \
ql/termstructures/credit/probabilitytraits.hpp \
ql/termstructures/credit/survivalprobabilitystructure.hpp \
ql/termstructures/defaulttermstructure.hpp \
ql/termstructures/inflation/inflationhelpers.hpp \
ql/termstructures/inflation/inflationtraits.hpp \
ql/termstructures/inflation/interpolatedyoyinflationcurve.hpp \
ql/termstructures/inflation/interpolatedzeroinflationcurve.hpp \
ql/termstructures/inflation/piecewiseyoyinflationcurve.hpp \
ql/termstructures/inflation/piecewisezeroinflationcurve.hpp \
ql/termstructures/inflation/seasonality.hpp \
ql/termstructures/inflationtermstructure.hpp \
ql/termstructures/interpolatedcurve.hpp \
ql/termstructures/iterativebootstrap.hpp \
ql/termstructures/localbootstrap.hpp \
ql/termstructures/volatility/abcd.hpp \
ql/termstructures/volatility/abcdcalibration.hpp \
ql/termstructures/volatility/capfloor/capfloortermvolatilitystructure.hpp \
ql/termstructures/volatility/capfloor/capfloortermvolcurve.hpp \
ql/termstructures/volatility/capfloor/capfloortermvolsurface.hpp \
ql/termstructures/volatility/capfloor/constantcapfloortermvol.hpp \
ql/termstructures/volatility/equityfx/blackconstantvol.hpp \
ql/termstructures/volatility/equityfx/blackvariancecurve.hpp \
ql/termstructures/volatility/equityfx/blackvariancesurface.hpp \
ql/termstructures/volatility/equityfx/blackvoltermstructure.hpp \
ql/termstructures/volatility/equityfx/impliedvoltermstructure.hpp \
ql/termstructures/volatility/equityfx/localconstantvol.hpp \
ql/termstructures/volatility/equityfx/localvolcurve.hpp \
ql/termstructures/volatility/equityfx/localvolsurface.hpp \
ql/termstructures/volatility/equityfx/localvoltermstructure.hpp \
ql/termstructures/volatility/flatsmilesection.hpp \
ql/termstructures/volatility/inflation/constantcpivolatility.hpp \
ql/termstructures/volatility/inflation/cpivolatilitystructure.hpp \
ql/termstructures/volatility/inflation/yoyinflationoptionletvolatilitystructure.hpp \
ql/termstructures/volatility/interpolatedsmilesection.hpp \
ql/termstructures/volatility/optionlet/capletvariancecurve.hpp \
ql/termstructures/volatility/optionlet/constantoptionletvol.hpp \
ql/termstructures/volatility/optionlet/optionletstripper.hpp \
ql/termstructures/volatility/optionlet/optionletstripper1.hpp \
ql/termstructures/volatility/optionlet/optionletstripper2.hpp \
ql/termstructures/volatility/optionlet/optionletvolatilitystructure.hpp \
ql/termstructures/volatility/optionlet/spreadedoptionletvol.hpp \
ql/termstructures/volatility/optionlet/strippedoptionlet.hpp \
ql/termstructures/volatility/optionlet/strippedoptionletadapter.hpp \
ql/termstructures/volatility/optionlet/strippedoptionletbase.hpp \
ql/termstructures/volatility/sabr.hpp \
ql/termstructures/volatility/sabrinterpolatedsmilesection.hpp \
ql/termstructures/volatility/sabrsmilesection.hpp \
ql/termstructures/volatility/smilesection.hpp \
ql/termstructures/volatility/spreadedsmilesection.hpp \
ql/termstructures/volatility/swaption/cmsmarket.hpp \
ql/termstructures/volatility/swaption/cmsmarketcalibration.hpp \
ql/termstructures/volatility/swaption/spreadedswaptionvol.hpp \
ql/termstructures/volatility/swaption/swaptionconstantvol.hpp \
ql/termstructures/volatility/swaption/swaptionvolcube.hpp \
ql/termstructures/volatility/swaption/swaptionvolcube1.hpp \
ql/termstructures/volatility/swaption/swaptionvolcube2.hpp \
ql/termstructures/volatility/swaption/swaptionvoldiscrete.hpp \
ql/termstructures/volatility/swaption/swaptionvolmatrix.hpp \
ql/termstructures/volatility/swaption/swaptionvolstructure.hpp \
ql/termstructures/voltermstructure.hpp \
ql/termstructures/yield/bondhelpers.hpp \
ql/termstructures/yield/bootstraptraits.hpp \
ql/termstructures/yield/discountcurve.hpp \
ql/termstructures/yield/drifttermstructure.hpp \
ql/termstructures/yield/fittedbonddiscountcurve.hpp \
ql/termstructures/yield/flatforward.hpp \
ql/termstructures/yield/forwardcurve.hpp \
ql/termstructures/yield/forwardspreadedtermstructure.hpp \
ql/termstructures/yield/forwardstructure.hpp \
ql/termstructures/yield/impliedtermstructure.hpp \
ql/termstructures/yield/nonlinearfittingmethods.hpp \
ql/termstructures/yield/oisratehelper.hpp \
ql/termstructures/yield/piecewiseyieldcurve.hpp \
ql/termstructures/yield/piecewisezerospreadedtermstructure.hpp \
ql/termstructures/yield/quantotermstructure.hpp \
ql/termstructures/yield/ratehelpers.hpp \
ql/termstructures/yield/zerocurve.hpp \
ql/termstructures/yield/zerospreadedtermstructure.hpp \
ql/termstructures/yield/zeroyieldstructure.hpp \
ql/termstructures/yieldtermstructure.hpp \
ql/time/businessdayconvention.hpp \
ql/time/calendar.hpp \
ql/time/calendars/argentina.hpp \
ql/time/calendars/australia.hpp \
ql/time/calendars/bespokecalendar.hpp \
ql/time/calendars/brazil.hpp \
ql/time/calendars/canada.hpp \
ql/time/calendars/china.hpp \
ql/time/calendars/czechrepublic.hpp \
ql/time/calendars/denmark.hpp \
ql/time/calendars/finland.hpp \
ql/time/calendars/germany.hpp \
ql/time/calendars/hongkong.hpp \
ql/time/calendars/hungary.hpp \
ql/time/calendars/iceland.hpp \
ql/time/calendars/india.hpp \
ql/time/calendars/indonesia.hpp \
ql/time/calendars/italy.hpp \
ql/time/calendars/japan.hpp \
ql/time/calendars/jointcalendar.hpp \
ql/time/calendars/mexico.hpp \
ql/time/calendars/newzealand.hpp \
ql/time/calendars/norway.hpp \
ql/time/calendars/nullcalendar.hpp \
ql/time/calendars/poland.hpp \
ql/time/calendars/russia.hpp \
ql/time/calendars/saudiarabia.hpp \
ql/time/calendars/singapore.hpp \
ql/time/calendars/slovakia.hpp \
ql/time/calendars/southafrica.hpp \
ql/time/calendars/southkorea.hpp \
ql/time/calendars/sweden.hpp \
ql/time/calendars/switzerland.hpp \
ql/time/calendars/taiwan.hpp \
ql/time/calendars/target.hpp \
ql/time/calendars/turkey.hpp \
ql/time/calendars/ukraine.hpp \
ql/time/calendars/unitedkingdom.hpp \
ql/time/calendars/unitedstates.hpp \
ql/time/calendars/weekendsonly.hpp \
ql/time/date.hpp \
ql/time/dategenerationrule.hpp \
ql/time/daycounter.hpp \
ql/time/daycounters/actual360.hpp \
ql/time/daycounters/actual365fixed.hpp \
ql/time/daycounters/actualactual.hpp \
ql/time/daycounters/business252.hpp \
ql/time/daycounters/one.hpp \
ql/time/daycounters/simpledaycounter.hpp \
ql/time/daycounters/thirty360.hpp \
ql/time/ecb.hpp \
ql/time/frequency.hpp \
ql/time/imm.hpp \
ql/time/period.hpp \
ql/time/schedule.hpp \
ql/time/timeunit.hpp \
ql/time/weekday.hpp \
ql/timegrid.hpp \
ql/timeseries.hpp \
ql/types.hpp \
ql/userconfig.hpp \
ql/utilities/clone.hpp \
ql/utilities/dataformatters.hpp \
ql/utilities/dataparsers.hpp \
ql/utilities/disposable.hpp \
ql/utilities/null.hpp \
ql/utilities/observablevalue.hpp \
ql/utilities/steppingiterator.hpp \
ql/utilities/tracing.hpp \
ql/utilities/vectors.hpp \
ql/version.hpp \
ql/volatilitymodel.hpp


#unix:!symbian {
#    maemo5 {
#        target.path = /opt/usr/lib
#    } else {
#        target.path = /usr/lib
#    }
#    INSTALLS += target
#}

#QUANTLIBQT_HOME_WIN = C:/QuantLib/QuantLibQt
#QUANTLIBQT_HOME_LINUX = /home/deriversatile/QuantLib/QuantLibQt
#OPENCVPATH_MSVC = D:/Qt/OpenCV-2.1.0-vs2008
#OPENCVPATH_MINGW = D:/Qt/OpenCV-2.1.0-mingw

#win32-msvc*{
#     INCLUDEPATH += $${OPENCVPATH_MSVC}/include
#     CONFIG(debug, debug|release) {
#         LIBS+=-L$${OPENCVPATH_MSVC}/lib/\
#               -lcxcore210d \
#               -lhighgui210d
#     } else {
#         LIBS += -L$${OPENCVPATH_MSVC}/lib/\
#                 -lcxcore210 \
#                 -lhighgui210
#    }
#}

#win32-g++{
#    INCLUDEPATH += $${OPENCVPATH_MINGW}/include
#    LIBS += -L$${OPENCVPATH_MINGW}/lib \
#            -lcxcore210 \
#            -lhighgui210
#}

#unix:LIBS += -lcv \
#    -lhighgui





EVERYTHING = $$SOURCES $$HEADERS
message("The project contains the following files:")
message($$EVERYTHING)
message(Qt version: $$[QT_VERSION])
message(Qt is installed in $$[QT_INSTALL_PREFIX])
message(Qt resources can be found in the following locations:)
message(Documentation: $$[QT_INSTALL_DOCS])
message(Header files: $$[QT_INSTALL_HEADERS])
message(Libraries: $$[QT_INSTALL_LIBS])
message(Binary files (executables): $$[QT_INSTALL_BINS])
message(Plugins: $$[QT_INSTALL_PLUGINS])
message(Data files: $$[QT_INSTALL_DATA])
message(Translation files: $$[QT_INSTALL_TRANSLATIONS])
message(Settings: $$[QT_INSTALL_SETTINGS])
message(Examples: $$[QT_INSTALL_EXAMPLES])
message(Demonstrations: $$[QT_INSTALL_DEMOS])
message(QT_INSTALL_BINS: $$[QT_INSTALL_BINS])
message(QT_INSTALL_BINS moc: $$[QT_INSTALL_BINS]\\moc)
message(QT_INSTALL_BINS moc: $$[QT_INSTALL_BINS]/moc)
message(Home Directory: $$[HOME_DIR])
