all:
	cd QuantLibAddin && $(MAKE)
	cd Addins/C && $(MAKE)
	cd Addins/Calc && $(MAKE)
	cd Clients/C++ && $(MAKE)
	cd Clients/C && $(MAKE)

clean:
	cd QuantLibAddin && $(MAKE) clean
	cd Addins/C && $(MAKE) clean
	cd Addins/Calc && $(MAKE) clean
	cd Clients/C++ && $(MAKE) clean
	cd Clients/C && $(MAKE) clean
