<div id="header">
<div class="social">
<div class="g-plusone" data-size="medium"></div>
<div class="g-plus" data-action="share" data-annotation="bubble"></div>
</div>
<a href="http://quantlib.org">
<img class="titleimage"
 src="/images/QL-title.jpg" width="185" height="50" border="0"
 alt="QuantLib"></a>
<br>
<div class="subtitle">A free/open-source library for quantitative finance</div>
</div>

<script type="text/javascript">
  window.___gcfg = {parsetags: 'onload'};

  (function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/plusone.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
  })();
</script>
