
<div class="endmatter">
<hr>
<div class="center">
<p>Feedback and questions concerning this site and project can be
directed to
 the <a href=
"http://lists.sourceforge.net/lists/listinfo/quantlib-users">QuantLib-users</a>
mailing list or
the QuantLib administrator <a href=
"mailto:ferdinando.ametrano@NOSPAMquantlib.org">Ferdinando&nbsp;Ametrano</a>
(remove NOSPAM from the email address).</p>

</div>
</div>
<!-- Search Google -->
<div class="center">
<form method="GET" action="http://www.google.com/custom">
<table summary="Google Search Table" bgcolor="#FFFFFF"
cellspacing="0" border="0">
<tr valign="top">
<td><a href="http://www.google.com/search"><img src=
"http://www.google.com/logos/Logo_40wht.gif" border="0" alt=
"Google" align="middle"></a> </td>
<td><input type="text" name="q" size="31" maxlength="255" value=
""> <input type="submit" name="sa" value="Google Search"> <input
type="hidden" name="cof" value=
"LW:133;L:http://quantlib.org/images/QL-small.jpg;LH:97;AH:center;GL:0;S:http://quantlib.org;AWFID:413269840f71f554;">
 <span class="googlestyle"><input type="hidden" name="domains"
value="quantlib.org"><br>
<input type="radio" name="sitesearch" value="" checked> Search
WWW <input type="radio" name="sitesearch" value="quantlib.org">
Search quantlib.org</span> <br>
</td>
</tr>
</table>
</form>
</div>

<!-- Search Google -->


</td>
</tr>
</tbody>
</table>

