
<meta name="keywords" content="QuantLib, C++, library, finance, quantitative finance, quant, quants, analysts, developers, free software, opensource">
<meta name="resource-type" content="document">
<meta name="revisit-after" content="15 days">
<meta name="classification" content="Personal">
<meta name="robots" content="ALL">
<meta name="distribution" content="Global">
<meta name="rating" content="Safe For Kids">
<meta name="doc-type" content="Web Page">
<meta name="doc-rights" content="Public">
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<meta http-equiv="Content-Style-Type" content="text/ccs">
<meta http-equiv="Window-target" content="_top">
<meta http-equiv="Content-Language" content="en">
<meta name='viewport' content='width=device-width,initial-scale=1'/>
<link rel="stylesheet" href="/styles/quantlib.css" type="text/css">
<link rel="stylesheet" href="/styles/print.css" type="text/css" media="print">
<link rel="shortcut icon" href="/images/favicon.ico" type="image/x-icon">
<link rel="icon" href="/images/favicon.ico" type="image/x-icon">
<link href='http://fonts.googleapis.com/css?family=Merriweather:900|Open+Sans:400,700|Merriweather+Sans:800' rel='stylesheet' type='text/css'>
<script type="text/javascript">
<!-- hiding
if (self != window.top) {
window.open(location.href);
}
// done hiding -->
</script>

