<table
summary="Layout table: the first cell contains the body of the page, the second a navigation bar."
 class="layout">
  <tbody>
    <tr>
      <td class="navbar">
        <div class="center">
				<img src="images/QL-small.jpg" alt="QuantLib Logo" />
        </div>
        <ul class="navlinklist">

          <li><a class="navlink" href="index.html">Home&nbsp;page</a></li>

          <li><a class="navlink" href="status.html">Project Status</a></li>

          <li><a class="navlink" href="docs.html">Documentation</a></li>

          <li><a class="navlink" href="license.html">License</a></li>

          <li><a class="navlink" href="group.html">QuantLib Group</a></li>

        </ul>
        <hr />

        <h3 class="navbartitle">Development</h3>
        <ul>
          <li><a class="navlink"
					href="http://sourceforge.net/projects/quantlib">Project&nbsp;page</a></li>

          <li><a class="navlink"
          href="http://sourceforge.net/mail/?group_id=12740">Mailing
          lists</a></li>

          <li><a class="navlink"
          href="http://sourceforge.net/news/?group_id=12740">News</a></li>

          <li><a class="navlink"
          href="http://sourceforge.net/project/showfiles.php?group_id=12740">
          Download</a></li>

          <li><a class="navlink" href="cvs.html">CVS</a></li>

          <li><a class="navlink"
          href="http://sourceforge.net/bugs/?group_id=12740">Bug&nbsp;Report</a></li>

          <li><a class="navlink"
          href="http://sourceforge.net/patch/?group_id=12740">Patches</a></li>

          <li><a class="navlink" href="FAQ.html">Developer FAQ</a></li>

          <li><a class="navlink" href="style.html">Programming Style
					Guidelines</a></li>
        </ul>
        <hr />
        <h3 class="navbartitle">General Resources</h3>
        <ul>
          <li><a class="navlink" href="lists.html">Lists of interest</a></li>
        </ul>
        <hr />

        <div class="center">
          <strong>Hosted by</strong>
        <br />
              <a href="http://sourceforge.net"><img
							src="http://sourceforge.net/sflogo.php?group_id=12740"
							width="88" height="31" border="0" alt="SourceForge Logo" /></a>
        </div>
        <br />
				<a href="http://sourceforge.net/docman/?group_id=1">About SourceForge,
				Open Source, CVS, etc.</a>


      </td>

      <td class="main">
