
<div class="endmatter">
<hr>
<div class="center">
<p>Feedback and questions concerning this site and project can be
directed to
 the <a href=
"http://lists.sourceforge.net/lists/listinfo/quantlib-users">QuantLib-users</a>
mailing list or
the QuantLib administrator <a href=
"mailto:ferdinando.ametrano@quantlib.org">Ferdinando&nbsp;Ametrano</a>.</p>

</div>
</div>
<!-- Search Google -->
<center>
<FORM method=GET action=http://www.google.com/custom>
<TABLE bgcolor=#FFFFFF cellspacing=0 border=0>
<tr valign=top><td>
<A HREF=http://www.google.com/search>
<IMG SRC=http://www.google.com/logos/Logo_40wht.gif border=0 ALT=Google align=middle></A>
</td>
<td>
<INPUT TYPE=text name=q size=31 maxlength=255 value="">
<INPUT type=submit name=sa VALUE="Google Search">
<INPUT type=hidden name=cof VALUE="LW:133;L:http://quantlib.org/images/QL-small.jpg;LH:97;AH:center;GL:0;S:http://quantlib.org;AWFID:413269840f71f554;">
<font face=arial,sans-serif size=-1><input type=hidden name=domains value="quantlib.org"><br><input type=radio name=sitesearch value="" checked> Search WWW <input type=radio name=sitesearch value="quantlib.org"> Search quantlib.org </font><br>
</td></tr></TABLE>
</FORM>
</center>
<!-- Search Google -->

</td>
</tr>
</tbody>
</table>

