<div class="categorygroup">
<div class="category">
<h3 class="categorytitle">Get QuantLib</h3>
<p class=categorysummary>Head to our <a
href="./download.shtml">download</a> page to get the latest official
release, or check out the latest development version from our <a
href="./git.shtml">git</a> repository.
QuantLib is also available in <a href="./extensions.shtml">other
languages</a>.</p>
</div>

<div class="category">
<h3 class="categorytitle">Documentation</h3>
<p class=categorysummary><a href="./docs.shtml">Documentation is
available</a> in several formats from a number of sources. You can
also read our <a href="./install.shtml">Installation instructions</a>
to get QuantLib working on your computer.</p>
</div>

<div class="category">
<h3 class="categorytitle">Need Help?</h3>
<p class=categorysummary>If you need to ask a question, subscribe to
our <a href="./mailinglists.shtml">mailing list</a> and post it
there. Before doing that, though, you might want to look at the <a
href="./faq.shtml">FAQ</a> and check if it was already answered.</p>
</div>
</div>

<div class="categorygroup">
<div class="category">
<h3 class="categorytitle">Found a bug?</h3>
<p class=categorysummary>If you have a patch, open a pull request on <a href="https://github.com/lballabio/quantlib/pulls">GitHub</a> or post it to our <a href=
"http://sourceforge.net/tracker/?group_id=12740&amp;atid=312740">patch manager</a>.  Otherwise, report the bug on our <a href=
"http://sourceforge.net/tracker/?func=add&amp;group_id=12740&amp;atid=112740">issue tracker</a>.</p>
</div>

<div class="category">
<h3 class="categorytitle">Want to contribute?</h3>
<p class=categorysummary>Just fork our repository on <a
href="https://github.com/lballabio/quantlib">GitHub</a> and start
coding (instructions are <a
href="https://help.github.com/articles/fork-a-repo">here</a>).  Please
have a look at our <a href="./newdeveloper.shtml">developer intro</a>
and <a href="./style.shtml">guidelines</a>.</p>
</div>

<div class="category">
<h3 class="categorytitle">More info</h3>
<p class=categorysummary>Here is the QuantLib <a
href="./license.shtml">license</a>, the <a
href="/reference/group.html">list of contributors</a>, and the <a
href="/reference/history.html">version history</a>. The project page
on Sourceforge is available at <a
href="http://sourceforge.net/projects/quantlib">this link</a>.</p>
</div>
</div>

<div class="categorygroup">
<div class="sponsor">
<a href="http://opensource.org/docs/definition.html"><img src=
"/images/osi-certified-90x75.png" width="90" height="75" border="0"
alt="OSI Certification Mark"></a></div>

<div class="sponsor"><strong>Hosted by</strong><br>
<a href="http://sourceforge.net/projects/quantlib"><img
src="http://sflogo.sourceforge.net/sflogo.php?group_id=12740&amp;type=13"
width="120" height="30" border="0" alt="Get QuantLib at
SourceForge.net. Fast, secure and Free Open Source software downloads">
</a></div>

<div class="sponsor"><strong>Supported by</strong><br>
<a href="http://www.statpro.com"><img src=
"/images/statpro.jpg" width="98"
height="33" border="0" alt="StatPro Logo"></a></div>
</div>
