
/*
 Copyright (C) 2006, 2007 Eric Ehlers

 This file is part of QuantLib, a free-software/open-source library
 for financial quantitative analysts and developers - http://quantlib.org/

 QuantLib is free software: you can redistribute it and/or modify it
 under the terms of the QuantLib license.  You should have received a
 copy of the license along with this program; if not, please email
 <quantlib-dev@lists.sf.net>. The license is also available online at
 <http://quantlib.org/license.shtml>.

 This program is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE.  See the license for more details.
*/

#ifndef qlo_conversions_all_hpp
#define qlo_conversions_all_hpp

#include <oh/Conversions/coerce.hpp>
#include <oh/Conversions/getobjectlist.hpp>
#include <qlo/Conversions/conversions.hpp>
#include <qlo/Conversions/coercehandle.hpp>
#include <qlo/Conversions/coercelibrarydifferent.hpp>
#include <qlo/Conversions/coercelibrarysame.hpp>
#include <qlo/Conversions/coerceobject.hpp>
//#include <qlo/Conversions/coercequote.hpp>
//#include <qlo/Conversions/coercetermstructure.hpp>
#include <qlo/Conversions/varianttodate.hpp>
#include <qlo/Conversions/varianttoperiod.hpp>
#include <qlo/Conversions/varianttoquote.hpp>
#include <qlo/Conversions/varianttoquotehandle.hpp>
#include <qlo/Conversions/varianttosize.hpp>

// This is a temporary hack required to overcome a limitation in gensrc
// for autogenerated code in file QuantLibAddin/Addins/C++/ohfunctions.cpp.

namespace QuantLibAddin {
    using ObjectHandler::Object;
}

#endif

