// this file generated automatically by autogen.py
// editing this file manually is not recommended

#include <com/sun/star/uno/XInterface.idl>
#include <com/sun/star/beans/XPropertySet.idl>

module com {
  module sun {
    module star {
      module sheet {
        module addin {
          interface XQL: com::sun::star::uno::XInterface {

                // functions

                sequence < sequence < any > > qlQuery(
                        [in] string handleObject)
                    raises( com::sun::star::lang::IllegalArgumentException );

                string qlLogfile(
                        [in] string logFileName)
                    raises( com::sun::star::lang::IllegalArgumentException );

                // options

                sequence < sequence < any > > qlOptionAsianC(
                        [in] string handle,
                        [in] string handleStochastic,
                        [in] string average,
                        [in] string optionType,
                        [in] string payoff,
                        [in] double strike,
                        [in] string exercise,
                        [in] long exerciseDate,
                        [in] long settlementDate,
                        [in] string engine,
                        [in] long timeSteps)
                    raises( com::sun::star::lang::IllegalArgumentException );

                sequence < sequence < any > > qlOptionAsianD(
                        [in] string handle,
                        [in] string handleStochastic,
                        [in] string average,
                        [in] double runningAccumulator,
                        [in] long pastFixings,
                        [in] sequence < sequence < long  > > fixingDates,
                        [in] string optionType,
                        [in] string payoff,
                        [in] double strike,
                        [in] string exercise,
                        [in] long exerciseDate,
                        [in] long settlementDate,
                        [in] string engine,
                        [in] long timeSteps)
                    raises( com::sun::star::lang::IllegalArgumentException );

                sequence < sequence < any > > qlOptionBarrier(
                        [in] string handle,
                        [in] string handleStochastic,
                        [in] string typeBarrier,
                        [in] double barrier,
                        [in] double rebate,
                        [in] string optionType,
                        [in] string payoff,
                        [in] double strike,
                        [in] string exercise,
                        [in] long exerciseDate,
                        [in] long settlementDate,
                        [in] string engine,
                        [in] long timeSteps)
                    raises( com::sun::star::lang::IllegalArgumentException );

                sequence < sequence < any > > qlOptionBasket(
                        [in] string handle,
                        [in] sequence < sequence < string  > > handleStochastic,
                        [in] string basket,
                        [in] sequence < sequence < double  > > correlations,
                        [in] string optionType,
                        [in] double strike,
                        [in] string exercise,
                        [in] long exerciseDate,
                        [in] long settlementDate,
                        [in] string engine,
                        [in] long timeSteps)
                    raises( com::sun::star::lang::IllegalArgumentException );

                sequence < sequence < any > > qlOptionCliquet(
                        [in] string handle,
                        [in] string handleStochastic,
                        [in] sequence < sequence < long  > > resetDates,
                        [in] string optionType,
                        [in] double strike,
                        [in] long exerciseDate,
                        [in] string engine,
                        [in] long timeSteps)
                    raises( com::sun::star::lang::IllegalArgumentException );

                sequence < sequence < any > > qlOptionDividendVanilla(
                        [in] string handle,
                        [in] string handleStochastic,
                        [in] sequence < sequence < long  > > dividendDates,
                        [in] sequence < sequence < double  > > dividends,
                        [in] string optionType,
                        [in] string payoff,
                        [in] double strike,
                        [in] string exercise,
                        [in] long exerciseDate,
                        [in] long settlementDate,
                        [in] string engine,
                        [in] long timeSteps)
                    raises( com::sun::star::lang::IllegalArgumentException );

                sequence < sequence < any > > qlOptionForwardVanilla(
                        [in] string handle,
                        [in] string handleStochastic,
                        [in] double moneyness,
                        [in] long resetDate,
                        [in] string optionType,
                        [in] string payoff,
                        [in] double strike,
                        [in] string exercise,
                        [in] long exerciseDate,
                        [in] long settlementDate,
                        [in] string engine,
                        [in] long timeSteps)
                    raises( com::sun::star::lang::IllegalArgumentException );

                sequence < sequence < any > > qlOptionSetEngine(
                        [in] string handle,
                        [in] string engineName,
                        [in] long timeSteps)
                    raises( com::sun::star::lang::IllegalArgumentException );

                sequence < sequence < any > > qlStochasticProcess(
                        [in] string handle,
                        [in] double underlying,
                        [in] string dayCounter,
                        [in] long settlementDate,
                        [in] double riskFreeRate,
                        [in] double dividendYield,
                        [in] double volatility)
                    raises( com::sun::star::lang::IllegalArgumentException );

                sequence < sequence < any > > qlOptionVanilla(
                        [in] string handle,
                        [in] string handleStochastic,
                        [in] string optionType,
                        [in] string payoff,
                        [in] double strike,
                        [in] string exercise,
                        [in] long exerciseDate,
                        [in] long settlementDate,
                        [in] string engine,
                        [in] long timeSteps)
                    raises( com::sun::star::lang::IllegalArgumentException );

          };
        };
      };
    };
  };
};

