// this file generated automatically by autogen.py on Mon Jan 10 18:55:01 2005
// editing this file manually is not recommended

#include <com/sun/star/uno/XInterface.idl>
#include <com/sun/star/beans/XPropertySet.idl>

module com {
  module sun {
    module star {
      module sheet {
        module addin {
          interface XQL: com::sun::star::uno::XInterface {

                // functions

                sequence < sequence < any > > qlQuery(
                        [in] string handleObject)
                    raises( com::sun::star::lang::IllegalArgumentException );

                string qlLogfile(
                        [in] string logFileName)
                    raises( com::sun::star::lang::IllegalArgumentException );

                // options

                sequence < sequence < any > > qlBlackScholes(
                        [in] string handle,
                        [in] double dividendYield,
                        [in] double riskFreeRate,
                        [in] double volatility,
                        [in] double underlying,
                        [in] long todaysDate,
                        [in] long settlementDate)
                    raises( com::sun::star::lang::IllegalArgumentException );

                sequence < sequence < any > > qlOption(
                        [in] string handle,
                        [in] string handleStochastic,
                        [in] string typeOption,
                        [in] double strike,
                        [in] long timeSteps,
                        [in] long exerciseDate,
                        [in] long settlementDate)
                    raises( com::sun::star::lang::IllegalArgumentException );

                sequence < sequence < any > > qlOptionSetEngine(
                        [in] string handle,
                        [in] string engineName,
                        [in] long timeSteps)
                    raises( com::sun::star::lang::IllegalArgumentException );

          };
        };
      };
    };
  };
};

