#include <com/sun/star/uno/XInterface.idl>
#include <com/sun/star/beans/XPropertySet.idl>

module com {
  module sun {
    module star {
      module sheet {
        module addin {
            interface XQL: com::sun::star::uno::XInterface
            {
				long incrementNum( [in] long nValue )
					raises( com::sun::star::lang::IllegalArgumentException );

				// pricers
				sequence < sequence < any > > qlBlackScholes(
                        [in] string handle,
                        [in] double dividendYield,
                        [in] double riskFreeRate,
                        [in] double volatility,
                        [in] double underlying,
                        [in] long todaysDateNum,
                        [in] long settlementDateNum)
					raises( com::sun::star::lang::IllegalArgumentException );

				sequence < sequence < any > > qlOption(
                        [in] string handle,
                        [in] string handleStochastic,
                        [in] string typeOption,
						[in] double strike,
                        [in] long timeSteps,
                        [in] long exerciseDateNum,
                        [in] long settlementDateNum)
					raises( com::sun::star::lang::IllegalArgumentException );

				sequence < sequence < any > > qlOptionSetEngine(
                        [in] string handle,
                        [in] long engineID,
                        [in] long timeSteps)
					raises( com::sun::star::lang::IllegalArgumentException );

				// utilities
				sequence < sequence < any > > qlQuery(
                        [in] string handleObject)
					raises( com::sun::star::lang::IllegalArgumentException );

				string qlLogfile(
                        [in] string logFileName)
					raises( com::sun::star::lang::IllegalArgumentException );
            };
        };
      };
    };
  };
};
